/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountIds,
  AccountInfoDTO,
  AccountOrderByEnum,
  AccountPage,
  MerkleStateInfoDTO,
  ModelError,
  Order,
} from '../models/index';
import {
    AccountIdsFromJSON,
    AccountIdsToJSON,
    AccountInfoDTOFromJSON,
    AccountInfoDTOToJSON,
    AccountOrderByEnumFromJSON,
    AccountOrderByEnumToJSON,
    AccountPageFromJSON,
    AccountPageToJSON,
    MerkleStateInfoDTOFromJSON,
    MerkleStateInfoDTOToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
    OrderFromJSON,
    OrderToJSON,
} from '../models/index';

export interface GetAccountInfoRequest {
    accountId: string;
}

export interface GetAccountInfoMerkleRequest {
    accountId: string;
}

export interface GetAccountsInfoRequest {
    accountIds?: AccountIds;
}

export interface SearchAccountsRequest {
    address?: string;
    pageSize?: number;
    pageNumber?: number;
    offset?: string;
    order?: Order;
    orderBy?: AccountOrderByEnum;
    mosaicId?: string;
}

/**
 * 
 */
export class AccountRoutesApi extends runtime.BaseAPI {

    /**
     * Retrieves account data for a given account identifier. The response contains the account state including balance, importance, public key, linked keys, and activity buckets.  The `accountId` path parameter accepts either a public key or a Base32-encoded address. 
     * Get account information
     */
    async getAccountInfoRaw(requestParameters: GetAccountInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountInfoDTO>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getAccountInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountInfoDTOFromJSON(jsonValue));
    }

    /**
     * Retrieves account data for a given account identifier. The response contains the account state including balance, importance, public key, linked keys, and activity buckets.  The `accountId` path parameter accepts either a public key or a Base32-encoded address. 
     * Get account information
     */
    async getAccountInfo(requestParameters: GetAccountInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountInfoDTO> {
        const response = await this.getAccountInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the Merkle proof data for a given account. The Merkle path can be used to independently verify that the account state is included in the block state hash.  If no account state entry exists for the supplied account ID, the endpoint still returns a Merkle proof response, but it is a negative proof showing that no account state entry exists for the requested account.  The `accountId` path parameter accepts either a public key or a Base32-encoded address. 
     * Get account Merkle information
     */
    async getAccountInfoMerkleRaw(requestParameters: GetAccountInfoMerkleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MerkleStateInfoDTO>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getAccountInfoMerkle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{accountId}/merkle`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MerkleStateInfoDTOFromJSON(jsonValue));
    }

    /**
     * Retrieves the Merkle proof data for a given account. The Merkle path can be used to independently verify that the account state is included in the block state hash.  If no account state entry exists for the supplied account ID, the endpoint still returns a Merkle proof response, but it is a negative proof showing that no account state entry exists for the requested account.  The `accountId` path parameter accepts either a public key or a Base32-encoded address. 
     * Get account Merkle information
     */
    async getAccountInfoMerkle(requestParameters: GetAccountInfoMerkleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MerkleStateInfoDTO> {
        const response = await this.getAccountInfoMerkleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves account data for multiple accounts in a single request. This is the batch equivalent of the single-account endpoint.  The request body accepts either an array of public keys or an array of addresses (not both). If both `publicKeys` and `addresses` are provided, the request is invalid and the server returns `409` error. 
     * Get accounts information
     */
    async getAccountsInfoRaw(requestParameters: GetAccountsInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountInfoDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/accounts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountIdsToJSON(requestParameters['accountIds']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountInfoDTOFromJSON));
    }

    /**
     * Retrieves account data for multiple accounts in a single request. This is the batch equivalent of the single-account endpoint.  The request body accepts either an array of public keys or an array of addresses (not both). If both `publicKeys` and `addresses` are provided, the request is invalid and the server returns `409` error. 
     * Get accounts information
     */
    async getAccountsInfo(requestParameters: GetAccountsInfoRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountInfoDTO>> {
        const response = await this.getAccountsInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of accounts matching the given criteria.  Results can be filtered by `address` and `mosaicId` (mosaic ownership), and ordered by `id` or `balance`. Standard pagination parameters (`pageSize`, `pageNumber`, `offset`, `order`) apply. The `orderBy` parameter supports `id` and `balance`; when using `orderBy=balance`, the `mosaicId` filter is required. The `offset` value must match the `orderBy` field. 
     * Search accounts
     */
    async searchAccountsRaw(requestParameters: SearchAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountPage>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['mosaicId'] != null) {
            queryParameters['mosaicId'] = requestParameters['mosaicId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountPageFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of accounts matching the given criteria.  Results can be filtered by `address` and `mosaicId` (mosaic ownership), and ordered by `id` or `balance`. Standard pagination parameters (`pageSize`, `pageNumber`, `offset`, `order`) apply. The `orderBy` parameter supports `id` and `balance`; when using `orderBy=balance`, the `mosaicId` filter is required. The `offset` value must match the `orderBy` field. 
     * Search accounts
     */
    async searchAccounts(requestParameters: SearchAccountsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountPage> {
        const response = await this.searchAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
