/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnnounceTransactionInfoDTO,
  Cosignature,
  ModelError,
  Order,
  TransactionIds,
  TransactionInfoDTO,
  TransactionPage,
  TransactionPayload,
  TransactionTypeEnum,
} from '../models/index';
import {
    AnnounceTransactionInfoDTOFromJSON,
    AnnounceTransactionInfoDTOToJSON,
    CosignatureFromJSON,
    CosignatureToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
    OrderFromJSON,
    OrderToJSON,
    TransactionIdsFromJSON,
    TransactionIdsToJSON,
    TransactionInfoDTOFromJSON,
    TransactionInfoDTOToJSON,
    TransactionPageFromJSON,
    TransactionPageToJSON,
    TransactionPayloadFromJSON,
    TransactionPayloadToJSON,
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumToJSON,
} from '../models/index';

export interface AnnounceCosignatureTransactionRequest {
    cosignature: Cosignature;
}

export interface AnnouncePartialTransactionRequest {
    transactionPayload: TransactionPayload;
}

export interface AnnounceTransactionRequest {
    transactionPayload: TransactionPayload;
}

export interface GetConfirmedTransactionRequest {
    transactionId: string;
}

export interface GetConfirmedTransactionsRequest {
    transactionIds: TransactionIds;
}

export interface GetPartialTransactionRequest {
    transactionId: string;
}

export interface GetPartialTransactionsRequest {
    transactionIds: TransactionIds;
}

export interface GetUnconfirmedTransactionRequest {
    transactionId: string;
}

export interface GetUnconfirmedTransactionsRequest {
    transactionIds: TransactionIds;
}

export interface SearchConfirmedTransactionsRequest {
    address?: string;
    recipientAddress?: string;
    signerPublicKey?: string;
    height?: string;
    fromHeight?: string;
    toHeight?: string;
    fromTransferAmount?: string;
    toTransferAmount?: string;
    type?: Array<TransactionTypeEnum>;
    embedded?: boolean;
    transferMosaicId?: string;
    pageSize?: number;
    pageNumber?: number;
    offset?: string;
    order?: Order;
}

export interface SearchPartialTransactionsRequest {
    address?: string;
    recipientAddress?: string;
    signerPublicKey?: string;
    height?: string;
    fromHeight?: string;
    toHeight?: string;
    fromTransferAmount?: string;
    toTransferAmount?: string;
    type?: Array<TransactionTypeEnum>;
    embedded?: boolean;
    transferMosaicId?: string;
    pageSize?: number;
    pageNumber?: number;
    offset?: string;
    order?: Order;
}

export interface SearchUnconfirmedTransactionsRequest {
    address?: string;
    recipientAddress?: string;
    signerPublicKey?: string;
    height?: string;
    fromHeight?: string;
    toHeight?: string;
    fromTransferAmount?: string;
    toTransferAmount?: string;
    type?: Array<TransactionTypeEnum>;
    embedded?: boolean;
    transferMosaicId?: string;
    pageSize?: number;
    pageNumber?: number;
    offset?: string;
    order?: Order;
}

/**
 * 
 */
export class TransactionRoutesApi extends runtime.BaseAPI {

    /**
     * Broadcasts a detached cosignature for an aggregate bonded transaction to the network through this node.  The request must contain the detached cosignature fields: cosignature version, signer public key, cosignature signature, and the parent aggregate transaction hash. Detached cosignatures are normally created client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  Acceptance by this node does not mean the parent aggregate bonded transaction is already confirmed on-chain. The cosignature still needs to be propagated and processed by the network.  To verify the effect of the cosignature, query the **parent aggregate bonded transaction**, for example with [`GET /transactionStatus/{hash}`](/transactionStatus/{hash}) using the parent aggregate transaction hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce a cosignature transaction
     */
    async announceCosignatureTransactionRaw(requestParameters: AnnounceCosignatureTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnounceTransactionInfoDTO>> {
        if (requestParameters['cosignature'] == null) {
            throw new runtime.RequiredError(
                'cosignature',
                'Required parameter "cosignature" was null or undefined when calling announceCosignatureTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions/cosignature`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CosignatureToJSON(requestParameters['cosignature']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnounceTransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Broadcasts a detached cosignature for an aggregate bonded transaction to the network through this node.  The request must contain the detached cosignature fields: cosignature version, signer public key, cosignature signature, and the parent aggregate transaction hash. Detached cosignatures are normally created client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  Acceptance by this node does not mean the parent aggregate bonded transaction is already confirmed on-chain. The cosignature still needs to be propagated and processed by the network.  To verify the effect of the cosignature, query the **parent aggregate bonded transaction**, for example with [`GET /transactionStatus/{hash}`](/transactionStatus/{hash}) using the parent aggregate transaction hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce a cosignature transaction
     */
    async announceCosignatureTransaction(requestParameters: AnnounceCosignatureTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnounceTransactionInfoDTO> {
        const response = await this.announceCosignatureTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Broadcasts a signed aggregate bonded transaction to the network through this node.  The request must contain the serialized aggregate bonded transaction payload in hexadecimal form. Transactions are normally created and signed client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  Acceptance by this node does not mean the transaction is already part of the blockchain. The transaction still needs to be validated and confirmed by the network.  To verify the final result, query `GET /transactionStatus/{hash}` on the same node that received the announce request. If that node drops the transaction before propagation, other nodes may not know the transaction at all and can return `404` for the same hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce an aggregate bonded transaction
     */
    async announcePartialTransactionRaw(requestParameters: AnnouncePartialTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnounceTransactionInfoDTO>> {
        if (requestParameters['transactionPayload'] == null) {
            throw new runtime.RequiredError(
                'transactionPayload',
                'Required parameter "transactionPayload" was null or undefined when calling announcePartialTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions/partial`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionPayloadToJSON(requestParameters['transactionPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnounceTransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Broadcasts a signed aggregate bonded transaction to the network through this node.  The request must contain the serialized aggregate bonded transaction payload in hexadecimal form. Transactions are normally created and signed client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  Acceptance by this node does not mean the transaction is already part of the blockchain. The transaction still needs to be validated and confirmed by the network.  To verify the final result, query `GET /transactionStatus/{hash}` on the same node that received the announce request. If that node drops the transaction before propagation, other nodes may not know the transaction at all and can return `404` for the same hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce an aggregate bonded transaction
     */
    async announcePartialTransaction(requestParameters: AnnouncePartialTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnounceTransactionInfoDTO> {
        const response = await this.announcePartialTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Broadcasts a signed transaction to the network through this node.  The request must contain the serialized transaction payload in hexadecimal form. Transactions are normally created and signed client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  The [catbuffer library](https://github.com/symbol/symbol/tree/main/catbuffer) defines the binary serialization format used by Symbol entities.  Acceptance by this node does not mean the transaction is already part of the blockchain. The transaction still needs to be validated and confirmed by the network.  To verify the final result, query `GET /transactionStatus/{hash}` on the same node that received the announce request. If that node drops the transaction before propagation, other nodes may not know the transaction at all and can return `404` for the same hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce a new transaction
     */
    async announceTransactionRaw(requestParameters: AnnounceTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnounceTransactionInfoDTO>> {
        if (requestParameters['transactionPayload'] == null) {
            throw new runtime.RequiredError(
                'transactionPayload',
                'Required parameter "transactionPayload" was null or undefined when calling announceTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionPayloadToJSON(requestParameters['transactionPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnounceTransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Broadcasts a signed transaction to the network through this node.  The request must contain the serialized transaction payload in hexadecimal form. Transactions are normally created and signed client-side with a [Symbol SDK](https://docs.symbol.dev/sdk.html) and then announced with this endpoint.  The [catbuffer library](https://github.com/symbol/symbol/tree/main/catbuffer) defines the binary serialization format used by Symbol entities.  Acceptance by this node does not mean the transaction is already part of the blockchain. The transaction still needs to be validated and confirmed by the network.  To verify the final result, query `GET /transactionStatus/{hash}` on the same node that received the announce request. If that node drops the transaction before propagation, other nodes may not know the transaction at all and can return `404` for the same hash. Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection and may be evicted as new entries arrive. 
     * Announce a new transaction
     */
    async announceTransaction(requestParameters: AnnounceTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnounceTransactionInfoDTO> {
        const response = await this.announceTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns confirmed transaction information given a transaction ID assigned by the node or transaction hash.  Use this endpoint when you need on-chain transaction data (the transaction is already included in a block). Use `getUnconfirmedTransaction` while the transaction is still in a node\'s unconfirmed pool, and use `getPartialTransaction` for aggregate bonded transactions waiting for cosignatures. 
     * Get confirmed transaction information
     */
    async getConfirmedTransactionRaw(requestParameters: GetConfirmedTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionInfoDTO>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getConfirmedTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/confirmed/{transactionId}`;
        urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Returns confirmed transaction information given a transaction ID assigned by the node or transaction hash.  Use this endpoint when you need on-chain transaction data (the transaction is already included in a block). Use `getUnconfirmedTransaction` while the transaction is still in a node\'s unconfirmed pool, and use `getPartialTransaction` for aggregate bonded transactions waiting for cosignatures. 
     * Get confirmed transaction information
     */
    async getConfirmedTransaction(requestParameters: GetConfirmedTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionInfoDTO> {
        const response = await this.getConfirmedTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns confirmed transactions for the list of identifiers in the request body. Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/confirmed` and `GET /transactions/confirmed/{transactionId}`.  Use this endpoint when you need on-chain data for multiple transactions in one call. Use `getUnconfirmedTransactions` for transactions still pending in a node pool, and use `getPartialTransactions` for aggregate bonded transactions waiting for cosignatures. 
     * Get confirmed transactions information
     */
    async getConfirmedTransactionsRaw(requestParameters: GetConfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransactionInfoDTO>>> {
        if (requestParameters['transactionIds'] == null) {
            throw new runtime.RequiredError(
                'transactionIds',
                'Required parameter "transactionIds" was null or undefined when calling getConfirmedTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions/confirmed`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionIdsToJSON(requestParameters['transactionIds']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionInfoDTOFromJSON));
    }

    /**
     * Returns confirmed transactions for the list of identifiers in the request body. Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/confirmed` and `GET /transactions/confirmed/{transactionId}`.  Use this endpoint when you need on-chain data for multiple transactions in one call. Use `getUnconfirmedTransactions` for transactions still pending in a node pool, and use `getPartialTransactions` for aggregate bonded transactions waiting for cosignatures. 
     * Get confirmed transactions information
     */
    async getConfirmedTransactions(requestParameters: GetConfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransactionInfoDTO>> {
        const response = await this.getConfirmedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one partial transaction identified by the path value. Partial transactions are aggregate bonded transactions waiting for the remaining cosignatures.  The path accepts either the transaction ID assigned by the node or the transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/partial` and `GET /transactions/partial/{transactionId}`.  Use this endpoint for aggregate bonded transactions before they are fully cosigned. Use `getUnconfirmedTransaction` for non-partial transactions that are in a node\'s unconfirmed pool, and use `getConfirmedTransaction` once the transaction is confirmed on-chain. 
     * Get partial transaction information
     */
    async getPartialTransactionRaw(requestParameters: GetPartialTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionInfoDTO>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getPartialTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/partial/{transactionId}`;
        urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Returns one partial transaction identified by the path value. Partial transactions are aggregate bonded transactions waiting for the remaining cosignatures.  The path accepts either the transaction ID assigned by the node or the transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/partial` and `GET /transactions/partial/{transactionId}`.  Use this endpoint for aggregate bonded transactions before they are fully cosigned. Use `getUnconfirmedTransaction` for non-partial transactions that are in a node\'s unconfirmed pool, and use `getConfirmedTransaction` once the transaction is confirmed on-chain. 
     * Get partial transaction information
     */
    async getPartialTransaction(requestParameters: GetPartialTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionInfoDTO> {
        const response = await this.getPartialTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns partial transactions for the list of identifiers in the request body. Partial transactions are aggregate bonded transactions waiting for the remaining cosignatures.  Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/partial` and `GET /transactions/partial/{transactionId}`.  Use this endpoint for aggregate bonded transactions that still wait for required cosignatures. Use `getUnconfirmedTransactions` for non-partial pending transactions accepted by a node but not yet included in a block, and use `getConfirmedTransactions` once transactions are confirmed on-chain. 
     * Get information about partial transactions
     */
    async getPartialTransactionsRaw(requestParameters: GetPartialTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransactionInfoDTO>>> {
        if (requestParameters['transactionIds'] == null) {
            throw new runtime.RequiredError(
                'transactionIds',
                'Required parameter "transactionIds" was null or undefined when calling getPartialTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions/partial`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionIdsToJSON(requestParameters['transactionIds']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionInfoDTOFromJSON));
    }

    /**
     * Returns partial transactions for the list of identifiers in the request body. Partial transactions are aggregate bonded transactions waiting for the remaining cosignatures.  Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/partial` and `GET /transactions/partial/{transactionId}`.  Use this endpoint for aggregate bonded transactions that still wait for required cosignatures. Use `getUnconfirmedTransactions` for non-partial pending transactions accepted by a node but not yet included in a block, and use `getConfirmedTransactions` once transactions are confirmed on-chain. 
     * Get information about partial transactions
     */
    async getPartialTransactions(requestParameters: GetPartialTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransactionInfoDTO>> {
        const response = await this.getPartialTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one unconfirmed transaction identified by the path value. An unconfirmed transaction is accepted by a node and pending inclusion in a block.  The path accepts either the transaction ID assigned by the node or the transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/unconfirmed` and `GET /transactions/unconfirmed/{transactionId}`.  Use this endpoint while a transaction is accepted by a node but not yet included in a block. Use `getConfirmedTransaction` once it is confirmed on-chain, and use `getPartialTransaction` for aggregate bonded transactions waiting for cosignatures. 
     * Get unconfirmed transaction information
     */
    async getUnconfirmedTransactionRaw(requestParameters: GetUnconfirmedTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionInfoDTO>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getUnconfirmedTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/unconfirmed/{transactionId}`;
        urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionInfoDTOFromJSON(jsonValue));
    }

    /**
     * Returns one unconfirmed transaction identified by the path value. An unconfirmed transaction is accepted by a node and pending inclusion in a block.  The path accepts either the transaction ID assigned by the node or the transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/unconfirmed` and `GET /transactions/unconfirmed/{transactionId}`.  Use this endpoint while a transaction is accepted by a node but not yet included in a block. Use `getConfirmedTransaction` once it is confirmed on-chain, and use `getPartialTransaction` for aggregate bonded transactions waiting for cosignatures. 
     * Get unconfirmed transaction information
     */
    async getUnconfirmedTransaction(requestParameters: GetUnconfirmedTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionInfoDTO> {
        const response = await this.getUnconfirmedTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns unconfirmed transactions for the list of identifiers in the request body. Unconfirmed transactions are accepted by a node and pending inclusion in a block.  Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/unconfirmed` and `GET /transactions/unconfirmed/{transactionId}`.  Use this endpoint when checking multiple transactions that are accepted by a node but not yet included in a block. Use `getConfirmedTransactions` for on-chain transactions, and use `getPartialTransactions` for aggregate bonded transactions waiting for cosignatures. 
     * Get information about unconfirmed transactions
     */
    async getUnconfirmedTransactionsRaw(requestParameters: GetUnconfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransactionInfoDTO>>> {
        if (requestParameters['transactionIds'] == null) {
            throw new runtime.RequiredError(
                'transactionIds',
                'Required parameter "transactionIds" was null or undefined when calling getUnconfirmedTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transactions/unconfirmed`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionIdsToJSON(requestParameters['transactionIds']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionInfoDTOFromJSON));
    }

    /**
     * Returns unconfirmed transactions for the list of identifiers in the request body. Unconfirmed transactions are accepted by a node and pending inclusion in a block.  Each request item can be either a transaction ID assigned by the node or a transaction hash. Both values are returned by transaction retrieval and search endpoints, for example `GET /transactions/unconfirmed` and `GET /transactions/unconfirmed/{transactionId}`.  Use this endpoint when checking multiple transactions that are accepted by a node but not yet included in a block. Use `getConfirmedTransactions` for on-chain transactions, and use `getPartialTransactions` for aggregate bonded transactions waiting for cosignatures. 
     * Get information about unconfirmed transactions
     */
    async getUnconfirmedTransactions(requestParameters: GetUnconfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransactionInfoDTO>> {
        const response = await this.getUnconfirmedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of confirmed transactions matching the supplied filters.  Use this endpoint when you need on-chain transactions only (already included in blocks). Use `searchUnconfirmedTransactions` for transactions that are still pending in a node pool, and use `searchPartialTransactions` for aggregate bonded transactions waiting for cosignatures.  If a transaction was announced with an alias rather than an address, the address considered during filtering is the one resolved from that alias at confirmation time.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search confirmed transactions
     */
    async searchConfirmedTransactionsRaw(requestParameters: SearchConfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPage>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['recipientAddress'] != null) {
            queryParameters['recipientAddress'] = requestParameters['recipientAddress'];
        }

        if (requestParameters['signerPublicKey'] != null) {
            queryParameters['signerPublicKey'] = requestParameters['signerPublicKey'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['fromHeight'] != null) {
            queryParameters['fromHeight'] = requestParameters['fromHeight'];
        }

        if (requestParameters['toHeight'] != null) {
            queryParameters['toHeight'] = requestParameters['toHeight'];
        }

        if (requestParameters['fromTransferAmount'] != null) {
            queryParameters['fromTransferAmount'] = requestParameters['fromTransferAmount'];
        }

        if (requestParameters['toTransferAmount'] != null) {
            queryParameters['toTransferAmount'] = requestParameters['toTransferAmount'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['embedded'] != null) {
            queryParameters['embedded'] = requestParameters['embedded'];
        }

        if (requestParameters['transferMosaicId'] != null) {
            queryParameters['transferMosaicId'] = requestParameters['transferMosaicId'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/confirmed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPageFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of confirmed transactions matching the supplied filters.  Use this endpoint when you need on-chain transactions only (already included in blocks). Use `searchUnconfirmedTransactions` for transactions that are still pending in a node pool, and use `searchPartialTransactions` for aggregate bonded transactions waiting for cosignatures.  If a transaction was announced with an alias rather than an address, the address considered during filtering is the one resolved from that alias at confirmation time.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search confirmed transactions
     */
    async searchConfirmedTransactions(requestParameters: SearchConfirmedTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPage> {
        const response = await this.searchConfirmedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of partial transactions matching the supplied filters.  Use this endpoint for aggregate bonded transactions that still wait for required cosignatures. Use `searchUnconfirmedTransactions` for non-partial pending transactions, and use `searchConfirmedTransactions` once transactions are confirmed on-chain.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search partial transactions
     */
    async searchPartialTransactionsRaw(requestParameters: SearchPartialTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPage>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['recipientAddress'] != null) {
            queryParameters['recipientAddress'] = requestParameters['recipientAddress'];
        }

        if (requestParameters['signerPublicKey'] != null) {
            queryParameters['signerPublicKey'] = requestParameters['signerPublicKey'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['fromHeight'] != null) {
            queryParameters['fromHeight'] = requestParameters['fromHeight'];
        }

        if (requestParameters['toHeight'] != null) {
            queryParameters['toHeight'] = requestParameters['toHeight'];
        }

        if (requestParameters['fromTransferAmount'] != null) {
            queryParameters['fromTransferAmount'] = requestParameters['fromTransferAmount'];
        }

        if (requestParameters['toTransferAmount'] != null) {
            queryParameters['toTransferAmount'] = requestParameters['toTransferAmount'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['embedded'] != null) {
            queryParameters['embedded'] = requestParameters['embedded'];
        }

        if (requestParameters['transferMosaicId'] != null) {
            queryParameters['transferMosaicId'] = requestParameters['transferMosaicId'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/partial`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPageFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of partial transactions matching the supplied filters.  Use this endpoint for aggregate bonded transactions that still wait for required cosignatures. Use `searchUnconfirmedTransactions` for non-partial pending transactions, and use `searchConfirmedTransactions` once transactions are confirmed on-chain.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search partial transactions
     */
    async searchPartialTransactions(requestParameters: SearchPartialTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPage> {
        const response = await this.searchPartialTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of unconfirmed transactions matching the supplied filters.  Use this endpoint for transactions accepted by a node but not yet included in a block. Use `searchConfirmedTransactions` for on-chain transactions, and use `searchPartialTransactions` for aggregate bonded transactions waiting for cosignatures.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search unconfirmed transactions
     */
    async searchUnconfirmedTransactionsRaw(requestParameters: SearchUnconfirmedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPage>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['recipientAddress'] != null) {
            queryParameters['recipientAddress'] = requestParameters['recipientAddress'];
        }

        if (requestParameters['signerPublicKey'] != null) {
            queryParameters['signerPublicKey'] = requestParameters['signerPublicKey'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['fromHeight'] != null) {
            queryParameters['fromHeight'] = requestParameters['fromHeight'];
        }

        if (requestParameters['toHeight'] != null) {
            queryParameters['toHeight'] = requestParameters['toHeight'];
        }

        if (requestParameters['fromTransferAmount'] != null) {
            queryParameters['fromTransferAmount'] = requestParameters['fromTransferAmount'];
        }

        if (requestParameters['toTransferAmount'] != null) {
            queryParameters['toTransferAmount'] = requestParameters['toTransferAmount'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['embedded'] != null) {
            queryParameters['embedded'] = requestParameters['embedded'];
        }

        if (requestParameters['transferMosaicId'] != null) {
            queryParameters['transferMosaicId'] = requestParameters['transferMosaicId'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transactions/unconfirmed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPageFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of unconfirmed transactions matching the supplied filters.  Use this endpoint for transactions accepted by a node but not yet included in a block. Use `searchConfirmedTransactions` for on-chain transactions, and use `searchPartialTransactions` for aggregate bonded transactions waiting for cosignatures.  For cursor-style pagination on this endpoint, set `offset` to the `id` of the last transaction from the previous page. For general pagination strategy guidance, see the `offset` and `pageNumber` query parameter descriptions. 
     * Search unconfirmed transactions
     */
    async searchUnconfirmedTransactions(requestParameters: SearchUnconfirmedTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPage> {
        const response = await this.searchUnconfirmedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
