/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
import {
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumFromJSONTyped,
    TransactionTypeEnumToJSON,
    TransactionTypeEnumToJSONTyped,
} from './TransactionTypeEnum';
import type { AccountRestrictionFlagsEnum } from './AccountRestrictionFlagsEnum';
import {
    AccountRestrictionFlagsEnumFromJSON,
    AccountRestrictionFlagsEnumFromJSONTyped,
    AccountRestrictionFlagsEnumToJSON,
    AccountRestrictionFlagsEnumToJSONTyped,
} from './AccountRestrictionFlagsEnum';

/**
 * 
 * @export
 * @interface AccountOperationRestrictionTransactionBodyDTO
 */
export interface AccountOperationRestrictionTransactionBodyDTO {
    /**
     * 
     * @type {AccountRestrictionFlagsEnum}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionFlags: AccountRestrictionFlagsEnum;
    /**
     * Account restriction additions.
     * @type {Array<TransactionTypeEnum>}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionAdditions: Array<TransactionTypeEnum>;
    /**
     * Account restriction deletions.
     * @type {Array<TransactionTypeEnum>}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionDeletions: Array<TransactionTypeEnum>;
}



/**
 * Check if a given object implements the AccountOperationRestrictionTransactionBodyDTO interface.
 */
export function instanceOfAccountOperationRestrictionTransactionBodyDTO(value: Record<string, any>): value is AccountOperationRestrictionTransactionBodyDTO {
    if (!('restrictionFlags' in value) || value['restrictionFlags'] === undefined) return false;
    if (!('restrictionAdditions' in value) || value['restrictionAdditions'] === undefined) return false;
    if (!('restrictionDeletions' in value) || value['restrictionDeletions'] === undefined) return false;
    return true;
}

export function AccountOperationRestrictionTransactionBodyDTOFromJSON(json: any): AccountOperationRestrictionTransactionBodyDTO {
    return AccountOperationRestrictionTransactionBodyDTOFromJSONTyped(json, false);
}

export function AccountOperationRestrictionTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountOperationRestrictionTransactionBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'restrictionFlags': AccountRestrictionFlagsEnumFromJSON(json['restrictionFlags']),
        'restrictionAdditions': ((json['restrictionAdditions'] as Array<any>).map(TransactionTypeEnumFromJSON)),
        'restrictionDeletions': ((json['restrictionDeletions'] as Array<any>).map(TransactionTypeEnumFromJSON)),
    };
}

export function AccountOperationRestrictionTransactionBodyDTOToJSON(json: any): AccountOperationRestrictionTransactionBodyDTO {
    return AccountOperationRestrictionTransactionBodyDTOToJSONTyped(json, false);
}

export function AccountOperationRestrictionTransactionBodyDTOToJSONTyped(value?: AccountOperationRestrictionTransactionBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restrictionFlags': AccountRestrictionFlagsEnumToJSON(value['restrictionFlags']),
        'restrictionAdditions': ((value['restrictionAdditions'] as Array<any>).map(TransactionTypeEnumToJSON)),
        'restrictionDeletions': ((value['restrictionDeletions'] as Array<any>).map(TransactionTypeEnumToJSON)),
    };
}

