/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
import {
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumFromJSONTyped,
    TransactionTypeEnumToJSON,
    TransactionTypeEnumToJSONTyped,
} from './TransactionTypeEnum';

/**
 * 
 * @export
 * @interface AccountRestrictionDTOValuesInner
 */
export interface AccountRestrictionDTOValuesInner {
}

/**
 * Check if a given object implements the AccountRestrictionDTOValuesInner interface.
 */
export function instanceOfAccountRestrictionDTOValuesInner(value: Record<string, any>): value is AccountRestrictionDTOValuesInner {
    return true;
}

export function AccountRestrictionDTOValuesInnerFromJSON(json: any): AccountRestrictionDTOValuesInner {
    return AccountRestrictionDTOValuesInnerFromJSONTyped(json, false);
}

export function AccountRestrictionDTOValuesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRestrictionDTOValuesInner {
    return json;
}

export function AccountRestrictionDTOValuesInnerToJSON(json: any): AccountRestrictionDTOValuesInner {
    return AccountRestrictionDTOValuesInnerToJSONTyped(json, false);
}

export function AccountRestrictionDTOValuesInnerToJSONTyped(value?: AccountRestrictionDTOValuesInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

