/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountLinkVotingKeyDTO
 */
export interface AccountLinkVotingKeyDTO {
    /**
     * 
     * @type {string}
     * @memberof AccountLinkVotingKeyDTO
     */
    publicKey: string;
    /**
     * Finalization Epoch
     * @type {number}
     * @memberof AccountLinkVotingKeyDTO
     */
    startEpoch: number;
    /**
     * Finalization Epoch
     * @type {number}
     * @memberof AccountLinkVotingKeyDTO
     */
    endEpoch: number;
}

export function AccountLinkVotingKeyDTOFromJSON(json: any): AccountLinkVotingKeyDTO {
    return AccountLinkVotingKeyDTOFromJSONTyped(json, false);
}

export function AccountLinkVotingKeyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLinkVotingKeyDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': json['publicKey'],
        'startEpoch': json['startEpoch'],
        'endEpoch': json['endEpoch'],
    };
}

export function AccountLinkVotingKeyDTOToJSON(value?: AccountLinkVotingKeyDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
        'startEpoch': value.startEpoch,
        'endEpoch': value.endEpoch,
    };
}

