/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountNamesDTO } from './AccountNamesDTO';
import {
    AccountNamesDTOFromJSON,
    AccountNamesDTOFromJSONTyped,
    AccountNamesDTOToJSON,
    AccountNamesDTOToJSONTyped,
} from './AccountNamesDTO';

/**
 * 
 * @export
 * @interface AccountsNamesDTO
 */
export interface AccountsNamesDTO {
    /**
     * Array of account names.
     * @type {Array<AccountNamesDTO>}
     * @memberof AccountsNamesDTO
     */
    accountNames: Array<AccountNamesDTO>;
}

/**
 * Check if a given object implements the AccountsNamesDTO interface.
 */
export function instanceOfAccountsNamesDTO(value: Record<string, any>): value is AccountsNamesDTO {
    if (!('accountNames' in value) || value['accountNames'] === undefined) return false;
    return true;
}

export function AccountsNamesDTOFromJSON(json: any): AccountsNamesDTO {
    return AccountsNamesDTOFromJSONTyped(json, false);
}

export function AccountsNamesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsNamesDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNames': ((json['accountNames'] as Array<any>).map(AccountNamesDTOFromJSON)),
    };
}

export function AccountsNamesDTOToJSON(json: any): AccountsNamesDTO {
    return AccountsNamesDTOToJSONTyped(json, false);
}

export function AccountsNamesDTOToJSONTyped(value?: AccountsNamesDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNames': ((value['accountNames'] as Array<any>).map(AccountNamesDTOToJSON)),
    };
}

