/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountRestrictionFlagsEnum } from './AccountRestrictionFlagsEnum';
import {
    AccountRestrictionFlagsEnumFromJSON,
    AccountRestrictionFlagsEnumFromJSONTyped,
    AccountRestrictionFlagsEnumToJSON,
    AccountRestrictionFlagsEnumToJSONTyped,
} from './AccountRestrictionFlagsEnum';

/**
 * 
 * @export
 * @interface AccountMosaicRestrictionTransactionBodyDTO
 */
export interface AccountMosaicRestrictionTransactionBodyDTO {
    /**
     * 
     * @type {AccountRestrictionFlagsEnum}
     * @memberof AccountMosaicRestrictionTransactionBodyDTO
     */
    restrictionFlags: AccountRestrictionFlagsEnum;
    /**
     * Account restriction additions.
     * @type {Array<string>}
     * @memberof AccountMosaicRestrictionTransactionBodyDTO
     */
    restrictionAdditions: Array<string>;
    /**
     * Account restriction deletions.
     * @type {Array<string>}
     * @memberof AccountMosaicRestrictionTransactionBodyDTO
     */
    restrictionDeletions: Array<string>;
}



/**
 * Check if a given object implements the AccountMosaicRestrictionTransactionBodyDTO interface.
 */
export function instanceOfAccountMosaicRestrictionTransactionBodyDTO(value: Record<string, any>): value is AccountMosaicRestrictionTransactionBodyDTO {
    if (!('restrictionFlags' in value) || value['restrictionFlags'] === undefined) return false;
    if (!('restrictionAdditions' in value) || value['restrictionAdditions'] === undefined) return false;
    if (!('restrictionDeletions' in value) || value['restrictionDeletions'] === undefined) return false;
    return true;
}

export function AccountMosaicRestrictionTransactionBodyDTOFromJSON(json: any): AccountMosaicRestrictionTransactionBodyDTO {
    return AccountMosaicRestrictionTransactionBodyDTOFromJSONTyped(json, false);
}

export function AccountMosaicRestrictionTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMosaicRestrictionTransactionBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'restrictionFlags': AccountRestrictionFlagsEnumFromJSON(json['restrictionFlags']),
        'restrictionAdditions': json['restrictionAdditions'],
        'restrictionDeletions': json['restrictionDeletions'],
    };
}

export function AccountMosaicRestrictionTransactionBodyDTOToJSON(json: any): AccountMosaicRestrictionTransactionBodyDTO {
    return AccountMosaicRestrictionTransactionBodyDTOToJSONTyped(json, false);
}

export function AccountMosaicRestrictionTransactionBodyDTOToJSONTyped(value?: AccountMosaicRestrictionTransactionBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restrictionFlags': AccountRestrictionFlagsEnumToJSON(value['restrictionFlags']),
        'restrictionAdditions': value['restrictionAdditions'],
        'restrictionDeletions': value['restrictionDeletions'],
    };
}

