/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CosignatureDTO } from './CosignatureDTO';
import {
    CosignatureDTOFromJSON,
    CosignatureDTOFromJSONTyped,
    CosignatureDTOToJSON,
    CosignatureDTOToJSONTyped,
} from './CosignatureDTO';
import type { EmbeddedTransactionInfoDTO } from './EmbeddedTransactionInfoDTO';
import {
    EmbeddedTransactionInfoDTOFromJSON,
    EmbeddedTransactionInfoDTOFromJSONTyped,
    EmbeddedTransactionInfoDTOToJSON,
    EmbeddedTransactionInfoDTOToJSONTyped,
} from './EmbeddedTransactionInfoDTO';

/**
 * 
 * @export
 * @interface AggregateTransactionBodyExtendedDTO
 */
export interface AggregateTransactionBodyExtendedDTO {
    /**
     * 
     * @type {string}
     * @memberof AggregateTransactionBodyExtendedDTO
     */
    transactionsHash: string;
    /**
     * Array of transaction cosignatures.
     * @type {Array<CosignatureDTO>}
     * @memberof AggregateTransactionBodyExtendedDTO
     */
    cosignatures: Array<CosignatureDTO>;
    /**
     * Array of transactions initiated by different accounts.
     * @type {Array<EmbeddedTransactionInfoDTO>}
     * @memberof AggregateTransactionBodyExtendedDTO
     */
    transactions: Array<EmbeddedTransactionInfoDTO>;
}

/**
 * Check if a given object implements the AggregateTransactionBodyExtendedDTO interface.
 */
export function instanceOfAggregateTransactionBodyExtendedDTO(value: Record<string, any>): value is AggregateTransactionBodyExtendedDTO {
    if (!('transactionsHash' in value) || value['transactionsHash'] === undefined) return false;
    if (!('cosignatures' in value) || value['cosignatures'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function AggregateTransactionBodyExtendedDTOFromJSON(json: any): AggregateTransactionBodyExtendedDTO {
    return AggregateTransactionBodyExtendedDTOFromJSONTyped(json, false);
}

export function AggregateTransactionBodyExtendedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateTransactionBodyExtendedDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionsHash': json['transactionsHash'],
        'cosignatures': ((json['cosignatures'] as Array<any>).map(CosignatureDTOFromJSON)),
        'transactions': ((json['transactions'] as Array<any>).map(EmbeddedTransactionInfoDTOFromJSON)),
    };
}

export function AggregateTransactionBodyExtendedDTOToJSON(json: any): AggregateTransactionBodyExtendedDTO {
    return AggregateTransactionBodyExtendedDTOToJSONTyped(json, false);
}

export function AggregateTransactionBodyExtendedDTOToJSONTyped(value?: AggregateTransactionBodyExtendedDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionsHash': value['transactionsHash'],
        'cosignatures': ((value['cosignatures'] as Array<any>).map(CosignatureDTOToJSON)),
        'transactions': ((value['transactions'] as Array<any>).map(EmbeddedTransactionInfoDTOToJSON)),
    };
}

