/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Alias action:
 * * 0 - Unlink alias.
 * * 1 - Link alias.
 * @export
 */
export const AliasActionEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type AliasActionEnum = typeof AliasActionEnum[keyof typeof AliasActionEnum];


export function AliasActionEnumFromJSON(json: any): AliasActionEnum {
    return AliasActionEnumFromJSONTyped(json, false);
}

export function AliasActionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasActionEnum {
    return json as AliasActionEnum;
}

export function AliasActionEnumToJSON(value?: AliasActionEnum | null): any {
    return value as any;
}

