/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnounceTransactionInfoDTO
 */
export interface AnnounceTransactionInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof AnnounceTransactionInfoDTO
     */
    message: string;
}

/**
 * Check if a given object implements the AnnounceTransactionInfoDTO interface.
 */
export function instanceOfAnnounceTransactionInfoDTO(value: Record<string, any>): value is AnnounceTransactionInfoDTO {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AnnounceTransactionInfoDTOFromJSON(json: any): AnnounceTransactionInfoDTO {
    return AnnounceTransactionInfoDTOFromJSONTyped(json, false);
}

export function AnnounceTransactionInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnounceTransactionInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AnnounceTransactionInfoDTOToJSON(json: any): AnnounceTransactionInfoDTO {
    return AnnounceTransactionInfoDTOToJSONTyped(json, false);
}

export function AnnounceTransactionInfoDTOToJSONTyped(value?: AnnounceTransactionInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

