/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Informational response returned after a transaction announce request is accepted.
 * 
 * This object does not contain the announced transaction payload or its final execution result. It
 * only carries the node message associated with the announce request.
 * 
 * Acceptance by a node does not mean the transaction is already part of the blockchain. The
 * transaction still needs to be validated and confirmed by the network.
 * 
 * To verify the final result, query `GET /transactionStatus/{hash}` on the same node that received
 * the announce request. If that node drops the transaction before propagation, other nodes may not
 * know the transaction at all and can return `404` for the same hash.
 * 
 * In some cases the transaction can be dropped without any failure status being returned. Common causes include using
 * a fee below the minimum accepted by that node or using a generation hash seed that does not match the target network.
 * Transaction status availability is not guaranteed indefinitely: failed statuses are stored in a capped collection
 * and may be evicted as new entries arrive.
 * 
 * @export
 * @interface AnnounceTransactionInfoDTO
 */
export interface AnnounceTransactionInfoDTO {
    /**
     * Human-readable message returned by the node for the announce request.
     * @type {string}
     * @memberof AnnounceTransactionInfoDTO
     */
    message: string;
}

/**
 * Check if a given object implements the AnnounceTransactionInfoDTO interface.
 */
export function instanceOfAnnounceTransactionInfoDTO(value: Record<string, any>): value is AnnounceTransactionInfoDTO {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AnnounceTransactionInfoDTOFromJSON(json: any): AnnounceTransactionInfoDTO {
    return AnnounceTransactionInfoDTOFromJSONTyped(json, false);
}

export function AnnounceTransactionInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnounceTransactionInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AnnounceTransactionInfoDTOToJSON(json: any): AnnounceTransactionInfoDTO {
    return AnnounceTransactionInfoDTOToJSONTyped(json, false);
}

export function AnnounceTransactionInfoDTOToJSONTyped(value?: AnnounceTransactionInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

