/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockInfoDTOBlock,
    BlockInfoDTOBlockFromJSON,
    BlockInfoDTOBlockFromJSONTyped,
    BlockInfoDTOBlockToJSON,
} from './BlockInfoDTOBlock';
import {
    BlockMetaDTO,
    BlockMetaDTOFromJSON,
    BlockMetaDTOFromJSONTyped,
    BlockMetaDTOToJSON,
} from './BlockMetaDTO';

/**
 * 
 * @export
 * @interface BlockInfoDTO
 */
export interface BlockInfoDTO {
    /**
     * Internal resource identifier.
     * @type {string}
     * @memberof BlockInfoDTO
     */
    id: string;
    /**
     * 
     * @type {BlockMetaDTO}
     * @memberof BlockInfoDTO
     */
    meta: BlockMetaDTO;
    /**
     * 
     * @type {BlockInfoDTOBlock}
     * @memberof BlockInfoDTO
     */
    block: BlockInfoDTOBlock;
}

export function BlockInfoDTOFromJSON(json: any): BlockInfoDTO {
    return BlockInfoDTOFromJSONTyped(json, false);
}

export function BlockInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'meta': BlockMetaDTOFromJSON(json['meta']),
        'block': BlockInfoDTOBlockFromJSON(json['block']),
    };
}

export function BlockInfoDTOToJSON(value?: BlockInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'meta': BlockMetaDTOToJSON(value.meta),
        'block': BlockInfoDTOBlockToJSON(value.block),
    };
}

