/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockInfoDTO,
    BlockInfoDTOFromJSON,
    BlockInfoDTOFromJSONTyped,
    BlockInfoDTOToJSON,
} from './BlockInfoDTO';
import {
    Pagination,
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * 
 * @export
 * @interface BlockPage
 */
export interface BlockPage {
    /**
     * Array of blocks.
     * @type {Array<BlockInfoDTO>}
     * @memberof BlockPage
     */
    data: Array<BlockInfoDTO>;
    /**
     * 
     * @type {Pagination}
     * @memberof BlockPage
     */
    pagination: Pagination;
}

export function BlockPageFromJSON(json: any): BlockPage {
    return BlockPageFromJSONTyped(json, false);
}

export function BlockPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BlockInfoDTOFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function BlockPageToJSON(value?: BlockPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(BlockInfoDTOToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

