/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';

/**
 * Embedded transaction variant of `MosaicAddressRestrictionTransactionDTO`.
 * @export
 * @interface EmbeddedMosaicAddressRestrictionTransactionDTO
 */
export interface EmbeddedMosaicAddressRestrictionTransactionDTO {
    /**
     * 256-bit public key encoded as a hexadecimal string (64 hex characters).
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version. Indicates the schema variant for serialization and validation.
     * @type {number}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    version: number;
    /**
     * Network type (mainnet or testnet). Ensures the entity targets the correct network.
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * Entity type identifier (e.g. transaction type code, block type). Determines the entity schema.
     * @type {number}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    type: number;
    /**
     * Unresolved mosaic identifier.
     * If the most significant bit of byte 0 is set, the value contains a namespace ID alias
     * instead of a concrete mosaic ID.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    mosaicId: string;
    /**
     * Restriction key represented as a 64-bit hexadecimal value.
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    restrictionKey: string;
    /**
     * Unsigned 64-bit value associated with a mosaic restriction key, represented as a decimal string.
     * For address restrictions, it is the value assigned to the target address;
     * for global restrictions, it is the threshold evaluated with the restriction type.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    previousRestrictionValue: string;
    /**
     * Unsigned 64-bit value associated with a mosaic restriction key, represented as a decimal string.
     * For address restrictions, it is the value assigned to the target address;
     * for global restrictions, it is the threshold evaluated with the restriction type.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    newRestrictionValue: string;
    /**
     * Unresolved address encoded as a 48-character hexadecimal string (24 bytes).
     * If bit 0 of byte 0 is not set, the value represents a regular address.
     * Otherwise, it represents a namespace ID alias encoded as an unresolved address.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAddressRestrictionTransactionDTO
     */
    targetAddress: string;
}



/**
 * Check if a given object implements the EmbeddedMosaicAddressRestrictionTransactionDTO interface.
 */
export function instanceOfEmbeddedMosaicAddressRestrictionTransactionDTO(value: Record<string, any>): value is EmbeddedMosaicAddressRestrictionTransactionDTO {
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('mosaicId' in value) || value['mosaicId'] === undefined) return false;
    if (!('restrictionKey' in value) || value['restrictionKey'] === undefined) return false;
    if (!('previousRestrictionValue' in value) || value['previousRestrictionValue'] === undefined) return false;
    if (!('newRestrictionValue' in value) || value['newRestrictionValue'] === undefined) return false;
    if (!('targetAddress' in value) || value['targetAddress'] === undefined) return false;
    return true;
}

export function EmbeddedMosaicAddressRestrictionTransactionDTOFromJSON(json: any): EmbeddedMosaicAddressRestrictionTransactionDTO {
    return EmbeddedMosaicAddressRestrictionTransactionDTOFromJSONTyped(json, false);
}

export function EmbeddedMosaicAddressRestrictionTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedMosaicAddressRestrictionTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'mosaicId': json['mosaicId'],
        'restrictionKey': json['restrictionKey'],
        'previousRestrictionValue': json['previousRestrictionValue'],
        'newRestrictionValue': json['newRestrictionValue'],
        'targetAddress': json['targetAddress'],
    };
}

export function EmbeddedMosaicAddressRestrictionTransactionDTOToJSON(json: any): EmbeddedMosaicAddressRestrictionTransactionDTO {
    return EmbeddedMosaicAddressRestrictionTransactionDTOToJSONTyped(json, false);
}

export function EmbeddedMosaicAddressRestrictionTransactionDTOToJSONTyped(value?: EmbeddedMosaicAddressRestrictionTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'mosaicId': value['mosaicId'],
        'restrictionKey': value['restrictionKey'],
        'previousRestrictionValue': value['previousRestrictionValue'],
        'newRestrictionValue': value['newRestrictionValue'],
        'targetAddress': value['targetAddress'],
    };
}

