/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';

/**
 * Embedded transaction variant of `MultisigAccountModificationTransactionDTO`.
 * @export
 * @interface EmbeddedMultisigAccountModificationTransactionDTO
 */
export interface EmbeddedMultisigAccountModificationTransactionDTO {
    /**
     * 256-bit public key encoded as a hexadecimal string (64 hex characters).
     * @type {string}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version. Indicates the schema variant for serialization and validation.
     * @type {number}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    version: number;
    /**
     * Network type (mainnet or testnet). Ensures the entity targets the correct network.
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * Entity type identifier (e.g. transaction type code, block type). Determines the entity schema.
     * @type {number}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    type: number;
    /**
     * Relative change applied to the minimum number of cosignatory approvals required to remove a
     * cosignatory. When converting a regular account into a multisig account, the initial value is
     * derived from this delta because the previous threshold is zero.
     * 
     * @type {number}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    minRemovalDelta: number;
    /**
     * Relative change applied to the minimum number of cosignatory approvals required to approve a
     * transaction. When converting a regular account into a multisig account, the initial value is
     * derived from this delta because the previous threshold is zero.
     * 
     * @type {number}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    minApprovalDelta: number;
    /**
     * Cosignatory addresses to add to the multisig account.
     * Newly added cosignatories must opt in by cosigning the aggregate transaction.
     * 
     * @type {Array<string>}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    addressAdditions: Array<string>;
    /**
     * Cosignatory addresses to remove from the multisig account.
     * @type {Array<string>}
     * @memberof EmbeddedMultisigAccountModificationTransactionDTO
     */
    addressDeletions: Array<string>;
}



/**
 * Check if a given object implements the EmbeddedMultisigAccountModificationTransactionDTO interface.
 */
export function instanceOfEmbeddedMultisigAccountModificationTransactionDTO(value: Record<string, any>): value is EmbeddedMultisigAccountModificationTransactionDTO {
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('minRemovalDelta' in value) || value['minRemovalDelta'] === undefined) return false;
    if (!('minApprovalDelta' in value) || value['minApprovalDelta'] === undefined) return false;
    if (!('addressAdditions' in value) || value['addressAdditions'] === undefined) return false;
    if (!('addressDeletions' in value) || value['addressDeletions'] === undefined) return false;
    return true;
}

export function EmbeddedMultisigAccountModificationTransactionDTOFromJSON(json: any): EmbeddedMultisigAccountModificationTransactionDTO {
    return EmbeddedMultisigAccountModificationTransactionDTOFromJSONTyped(json, false);
}

export function EmbeddedMultisigAccountModificationTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedMultisigAccountModificationTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'minRemovalDelta': json['minRemovalDelta'],
        'minApprovalDelta': json['minApprovalDelta'],
        'addressAdditions': json['addressAdditions'],
        'addressDeletions': json['addressDeletions'],
    };
}

export function EmbeddedMultisigAccountModificationTransactionDTOToJSON(json: any): EmbeddedMultisigAccountModificationTransactionDTO {
    return EmbeddedMultisigAccountModificationTransactionDTOToJSONTyped(json, false);
}

export function EmbeddedMultisigAccountModificationTransactionDTOToJSONTyped(value?: EmbeddedMultisigAccountModificationTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'minRemovalDelta': value['minRemovalDelta'],
        'minApprovalDelta': value['minApprovalDelta'],
        'addressAdditions': value['addressAdditions'],
        'addressDeletions': value['addressDeletions'],
    };
}

