/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';
import type { AliasActionEnum } from './AliasActionEnum';
import {
    AliasActionEnumFromJSON,
    AliasActionEnumFromJSONTyped,
    AliasActionEnumToJSON,
    AliasActionEnumToJSONTyped,
} from './AliasActionEnum';

/**
 * Embedded transaction variant of `MosaicAliasTransactionDTO`.
 * @export
 * @interface EmbeddedMosaicAliasTransactionDTO
 */
export interface EmbeddedMosaicAliasTransactionDTO {
    /**
     * 256-bit public key encoded as a hexadecimal string (64 hex characters).
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version. Indicates the schema variant for serialization and validation.
     * @type {number}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    version: number;
    /**
     * Network type (mainnet or testnet). Ensures the entity targets the correct network.
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * Entity type identifier (e.g. transaction type code, block type). Determines the entity schema.
     * @type {number}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    type: number;
    /**
     * Unique [namespace](https://docs.symbol.dev/concepts/namespaces.html) identifier.
     * A 64-bit unsigned integer derived from the namespace name and its parent namespace ID,
     * encoded as a 16-character hexadecimal string.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    namespaceId: string;
    /**
     * Unique [mosaic](https://docs.symbol.dev/concepts/mosaic.html) identifier.
     * A 64-bit unsigned integer derived from the creator's address and a registration nonce,
     * encoded as a 16-character hexadecimal string.
     * 
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    mosaicId: string;
    /**
     * 
     * @type {AliasActionEnum}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    aliasAction: AliasActionEnum;
}



/**
 * Check if a given object implements the EmbeddedMosaicAliasTransactionDTO interface.
 */
export function instanceOfEmbeddedMosaicAliasTransactionDTO(value: Record<string, any>): value is EmbeddedMosaicAliasTransactionDTO {
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('namespaceId' in value) || value['namespaceId'] === undefined) return false;
    if (!('mosaicId' in value) || value['mosaicId'] === undefined) return false;
    if (!('aliasAction' in value) || value['aliasAction'] === undefined) return false;
    return true;
}

export function EmbeddedMosaicAliasTransactionDTOFromJSON(json: any): EmbeddedMosaicAliasTransactionDTO {
    return EmbeddedMosaicAliasTransactionDTOFromJSONTyped(json, false);
}

export function EmbeddedMosaicAliasTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedMosaicAliasTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'namespaceId': json['namespaceId'],
        'mosaicId': json['mosaicId'],
        'aliasAction': AliasActionEnumFromJSON(json['aliasAction']),
    };
}

export function EmbeddedMosaicAliasTransactionDTOToJSON(json: any): EmbeddedMosaicAliasTransactionDTO {
    return EmbeddedMosaicAliasTransactionDTOToJSONTyped(json, false);
}

export function EmbeddedMosaicAliasTransactionDTOToJSONTyped(value?: EmbeddedMosaicAliasTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'namespaceId': value['namespaceId'],
        'mosaicId': value['mosaicId'],
        'aliasAction': AliasActionEnumToJSON(value['aliasAction']),
    };
}

