/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedTransactionInfoDTO,
    EmbeddedTransactionInfoDTOFromJSON,
    EmbeddedTransactionInfoDTOFromJSONTyped,
    EmbeddedTransactionInfoDTOToJSON,
} from './EmbeddedTransactionInfoDTO';

/**
 * 
 * @export
 * @interface EmbeddedTransactionBodyDTO
 */
export interface EmbeddedTransactionBodyDTO {
    /**
     * Array of transactions initiated by different accounts.
     * @type {Array<EmbeddedTransactionInfoDTO>}
     * @memberof EmbeddedTransactionBodyDTO
     */
    transactions: Array<EmbeddedTransactionInfoDTO>;
}

export function EmbeddedTransactionBodyDTOFromJSON(json: any): EmbeddedTransactionBodyDTO {
    return EmbeddedTransactionBodyDTOFromJSONTyped(json, false);
}

export function EmbeddedTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedTransactionBodyDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactions': ((json['transactions'] as Array<any>).map(EmbeddedTransactionInfoDTOFromJSON)),
    };
}

export function EmbeddedTransactionBodyDTOToJSON(value?: EmbeddedTransactionBodyDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactions': ((value.transactions as Array<any>).map(EmbeddedTransactionInfoDTOToJSON)),
    };
}

