/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';
import type { AccountRestrictionFlagsEnum } from './AccountRestrictionFlagsEnum';
import {
    AccountRestrictionFlagsEnumFromJSON,
    AccountRestrictionFlagsEnumFromJSONTyped,
    AccountRestrictionFlagsEnumToJSON,
    AccountRestrictionFlagsEnumToJSONTyped,
} from './AccountRestrictionFlagsEnum';

/**
 * 
 * @export
 * @interface EmbeddedAccountMosaicRestrictionTransactionDTO
 */
export interface EmbeddedAccountMosaicRestrictionTransactionDTO {
    /**
     * Public key.
     * @type {string}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version.
     * @type {number}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    version: number;
    /**
     * 
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    type: number;
    /**
     * 
     * @type {AccountRestrictionFlagsEnum}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    restrictionFlags: AccountRestrictionFlagsEnum;
    /**
     * Account restriction additions.
     * @type {Array<string>}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    restrictionAdditions: Array<string>;
    /**
     * Account restriction deletions.
     * @type {Array<string>}
     * @memberof EmbeddedAccountMosaicRestrictionTransactionDTO
     */
    restrictionDeletions: Array<string>;
}



/**
 * Check if a given object implements the EmbeddedAccountMosaicRestrictionTransactionDTO interface.
 */
export function instanceOfEmbeddedAccountMosaicRestrictionTransactionDTO(value: Record<string, any>): value is EmbeddedAccountMosaicRestrictionTransactionDTO {
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('restrictionFlags' in value) || value['restrictionFlags'] === undefined) return false;
    if (!('restrictionAdditions' in value) || value['restrictionAdditions'] === undefined) return false;
    if (!('restrictionDeletions' in value) || value['restrictionDeletions'] === undefined) return false;
    return true;
}

export function EmbeddedAccountMosaicRestrictionTransactionDTOFromJSON(json: any): EmbeddedAccountMosaicRestrictionTransactionDTO {
    return EmbeddedAccountMosaicRestrictionTransactionDTOFromJSONTyped(json, false);
}

export function EmbeddedAccountMosaicRestrictionTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedAccountMosaicRestrictionTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'restrictionFlags': AccountRestrictionFlagsEnumFromJSON(json['restrictionFlags']),
        'restrictionAdditions': json['restrictionAdditions'],
        'restrictionDeletions': json['restrictionDeletions'],
    };
}

export function EmbeddedAccountMosaicRestrictionTransactionDTOToJSON(json: any): EmbeddedAccountMosaicRestrictionTransactionDTO {
    return EmbeddedAccountMosaicRestrictionTransactionDTOToJSONTyped(json, false);
}

export function EmbeddedAccountMosaicRestrictionTransactionDTOToJSONTyped(value?: EmbeddedAccountMosaicRestrictionTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'restrictionFlags': AccountRestrictionFlagsEnumToJSON(value['restrictionFlags']),
        'restrictionAdditions': value['restrictionAdditions'],
        'restrictionDeletions': value['restrictionDeletions'],
    };
}

