/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashLockNetworkPropertiesDTO
 */
export interface HashLockNetworkPropertiesDTO {
    /**
     * Amount that has to be locked per aggregate in partial cache.
     * @type {string}
     * @memberof HashLockNetworkPropertiesDTO
     */
    lockedFundsPerAggregate?: string;
    /**
     * Maximum number of blocks for which a hash lock can exist.
     * @type {string}
     * @memberof HashLockNetworkPropertiesDTO
     */
    maxHashLockDuration?: string;
}

export function HashLockNetworkPropertiesDTOFromJSON(json: any): HashLockNetworkPropertiesDTO {
    return HashLockNetworkPropertiesDTOFromJSONTyped(json, false);
}

export function HashLockNetworkPropertiesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashLockNetworkPropertiesDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lockedFundsPerAggregate': !exists(json, 'lockedFundsPerAggregate') ? undefined : json['lockedFundsPerAggregate'],
        'maxHashLockDuration': !exists(json, 'maxHashLockDuration') ? undefined : json['maxHashLockDuration'],
    };
}

export function HashLockNetworkPropertiesDTOToJSON(value?: HashLockNetworkPropertiesDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lockedFundsPerAggregate': value.lockedFundsPerAggregate,
        'maxHashLockDuration': value.maxHashLockDuration,
    };
}

