/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LockStatus,
    LockStatusFromJSON,
    LockStatusFromJSONTyped,
    LockStatusToJSON,
} from './LockStatus';

/**
 * 
 * @export
 * @interface HashLockEntryDTO
 */
export interface HashLockEntryDTO {
    /**
     * The version of the state
     * @type {number}
     * @memberof HashLockEntryDTO
     */
    version: number;
    /**
     * Address encoded using a 32-character set.
     * @type {string}
     * @memberof HashLockEntryDTO
     */
    ownerAddress: string;
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof HashLockEntryDTO
     */
    mosaicId: string;
    /**
     * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
     * @type {string}
     * @memberof HashLockEntryDTO
     */
    amount: string;
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof HashLockEntryDTO
     */
    endHeight: string;
    /**
     * 
     * @type {LockStatus}
     * @memberof HashLockEntryDTO
     */
    status: LockStatus;
    /**
     * 
     * @type {string}
     * @memberof HashLockEntryDTO
     */
    hash: string;
}

export function HashLockEntryDTOFromJSON(json: any): HashLockEntryDTO {
    return HashLockEntryDTOFromJSONTyped(json, false);
}

export function HashLockEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashLockEntryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
        'ownerAddress': json['ownerAddress'],
        'mosaicId': json['mosaicId'],
        'amount': json['amount'],
        'endHeight': json['endHeight'],
        'status': LockStatusFromJSON(json['status']),
        'hash': json['hash'],
    };
}

export function HashLockEntryDTOToJSON(value?: HashLockEntryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'ownerAddress': value.ownerAddress,
        'mosaicId': value.mosaicId,
        'amount': value.amount,
        'endHeight': value.endHeight,
        'status': LockStatusToJSON(value.status),
        'hash': value.hash,
    };
}

