/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Hash algorithm used to derive the secret from the revealed proof in secret lock and secret proof transactions:
 * - `0` (`SHA3_256`): proof hashed once with SHA3-256.
 * - `1` (`HASH_160`): proof hashed with SHA-256 and then with RIPEMD-160, similar to Bitcoin `OP_HASH160`.
 * - `2` (`HASH_256`): proof hashed twice with SHA-256, similar to Bitcoin `OP_HASH256`.
 * 
 * @export
 */
export const LockHashAlgorithmEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type LockHashAlgorithmEnum = typeof LockHashAlgorithmEnum[keyof typeof LockHashAlgorithmEnum];


export function instanceOfLockHashAlgorithmEnum(value: any): boolean {
    for (const key in LockHashAlgorithmEnum) {
        if (Object.prototype.hasOwnProperty.call(LockHashAlgorithmEnum, key)) {
            if (LockHashAlgorithmEnum[key as keyof typeof LockHashAlgorithmEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LockHashAlgorithmEnumFromJSON(json: any): LockHashAlgorithmEnum {
    return LockHashAlgorithmEnumFromJSONTyped(json, false);
}

export function LockHashAlgorithmEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockHashAlgorithmEnum {
    return json as LockHashAlgorithmEnum;
}

export function LockHashAlgorithmEnumToJSON(value?: LockHashAlgorithmEnum | null): any {
    return value as any;
}

export function LockHashAlgorithmEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LockHashAlgorithmEnum {
    return value as LockHashAlgorithmEnum;
}

