/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PositionEnum,
    PositionEnumFromJSON,
    PositionEnumFromJSONTyped,
    PositionEnumToJSON,
} from './PositionEnum';

/**
 * Each merkle path item is composed of a hash, and a position relative to the proofHash being evaluated.
 * @export
 * @interface MerklePathItemDTO
 */
export interface MerklePathItemDTO {
    /**
     * 
     * @type {PositionEnum}
     * @memberof MerklePathItemDTO
     */
    position?: PositionEnum;
    /**
     * 
     * @type {string}
     * @memberof MerklePathItemDTO
     */
    hash?: string;
}

export function MerklePathItemDTOFromJSON(json: any): MerklePathItemDTO {
    return MerklePathItemDTOFromJSONTyped(json, false);
}

export function MerklePathItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerklePathItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'position': !exists(json, 'position') ? undefined : PositionEnumFromJSON(json['position']),
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function MerklePathItemDTOToJSON(value?: MerklePathItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'position': PositionEnumToJSON(value.position),
        'hash': value.hash,
    };
}

