/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BmTreeSignature } from './BmTreeSignature';
import {
    BmTreeSignatureFromJSON,
    BmTreeSignatureFromJSONTyped,
    BmTreeSignatureToJSON,
    BmTreeSignatureToJSONTyped,
} from './BmTreeSignature';
import type { StageEnum } from './StageEnum';
import {
    StageEnumFromJSON,
    StageEnumFromJSONTyped,
    StageEnumToJSON,
    StageEnumToJSONTyped,
} from './StageEnum';

/**
 * 
 * @export
 * @interface MessageGroup
 */
export interface MessageGroup {
    /**
     * 
     * @type {StageEnum}
     * @memberof MessageGroup
     */
    stage: StageEnum;
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof MessageGroup
     */
    height: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageGroup
     */
    hashes: Array<string>;
    /**
     * 
     * @type {Array<BmTreeSignature>}
     * @memberof MessageGroup
     */
    signatures: Array<BmTreeSignature>;
}



/**
 * Check if a given object implements the MessageGroup interface.
 */
export function instanceOfMessageGroup(value: Record<string, any>): value is MessageGroup {
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('hashes' in value) || value['hashes'] === undefined) return false;
    if (!('signatures' in value) || value['signatures'] === undefined) return false;
    return true;
}

export function MessageGroupFromJSON(json: any): MessageGroup {
    return MessageGroupFromJSONTyped(json, false);
}

export function MessageGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': StageEnumFromJSON(json['stage']),
        'height': json['height'],
        'hashes': json['hashes'],
        'signatures': ((json['signatures'] as Array<any>).map(BmTreeSignatureFromJSON)),
    };
}

export function MessageGroupToJSON(json: any): MessageGroup {
    return MessageGroupToJSONTyped(json, false);
}

export function MessageGroupToJSONTyped(value?: MessageGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage': StageEnumToJSON(value['stage']),
        'height': value['height'],
        'hashes': value['hashes'],
        'signatures': ((value['signatures'] as Array<any>).map(BmTreeSignatureToJSON)),
    };
}

