/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataTypeEnum } from './MetadataTypeEnum';
import {
    MetadataTypeEnumFromJSON,
    MetadataTypeEnumFromJSONTyped,
    MetadataTypeEnumToJSON,
    MetadataTypeEnumToJSONTyped,
} from './MetadataTypeEnum';
import type { MetadataEntryDTOTargetId } from './MetadataEntryDTOTargetId';
import {
    MetadataEntryDTOTargetIdFromJSON,
    MetadataEntryDTOTargetIdFromJSONTyped,
    MetadataEntryDTOTargetIdToJSON,
    MetadataEntryDTOTargetIdToJSONTyped,
} from './MetadataEntryDTOTargetId';

/**
 * Full on-chain metadata entry identified by a composite hash.
 * @export
 * @interface MetadataEntryDTO
 */
export interface MetadataEntryDTO {
    /**
     * Version of the on-chain state serialization format. Incremented when the storage
     * schema of the entity changes (e.g. new fields are added), allowing the node to
     * deserialize entries written under earlier formats.
     * 
     * @type {number}
     * @memberof MetadataEntryDTO
     */
    version: number;
    /**
     * 256-bit hash encoded as a 64-character hexadecimal string.
     * @type {string}
     * @memberof MetadataEntryDTO
     */
    compositeHash: string;
    /**
     * Address encoded as a 48-character hexadecimal string (24 bytes).
     * The REST API returns addresses in this format. For Base32-encoded addresses (39 chars) see `Address`.
     * 
     * @type {string}
     * @memberof MetadataEntryDTO
     */
    sourceAddress: string;
    /**
     * Address encoded as a 48-character hexadecimal string (24 bytes).
     * The REST API returns addresses in this format. For Base32-encoded addresses (39 chars) see `Address`.
     * 
     * @type {string}
     * @memberof MetadataEntryDTO
     */
    targetAddress: string;
    /**
     * 64-bit key assigned by the metadata creator to identify the metadata entry within the source and target context.
     * @type {string}
     * @memberof MetadataEntryDTO
     */
    scopedMetadataKey: string;
    /**
     * 
     * @type {MetadataEntryDTOTargetId}
     * @memberof MetadataEntryDTO
     */
    targetId?: MetadataEntryDTOTargetId;
    /**
     * 
     * @type {MetadataTypeEnum}
     * @memberof MetadataEntryDTO
     */
    metadataType: MetadataTypeEnum;
    /**
     * Size of a metadata value or metadata value update payload, in bytes.
     * In metadata transactions, when no previous value exists, or when the value grows, this is the new
     * value size after applying the update. When the value shrinks, this is the previous stored value size
     * before truncation.
     * 
     * @type {number}
     * @memberof MetadataEntryDTO
     */
    valueSize: number;
    /**
     * Metadata value encoded as hex.
     * In metadata transactions, this field carries the metadata value update payload.
     * When no previous value exists, it contains the new value.
     * When updating existing metadata, it contains the byte-wise XOR of the previous value and the new value.
     * 
     * @type {string}
     * @memberof MetadataEntryDTO
     */
    value: string;
}



/**
 * Check if a given object implements the MetadataEntryDTO interface.
 */
export function instanceOfMetadataEntryDTO(value: Record<string, any>): value is MetadataEntryDTO {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('compositeHash' in value) || value['compositeHash'] === undefined) return false;
    if (!('sourceAddress' in value) || value['sourceAddress'] === undefined) return false;
    if (!('targetAddress' in value) || value['targetAddress'] === undefined) return false;
    if (!('scopedMetadataKey' in value) || value['scopedMetadataKey'] === undefined) return false;
    if (!('metadataType' in value) || value['metadataType'] === undefined) return false;
    if (!('valueSize' in value) || value['valueSize'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MetadataEntryDTOFromJSON(json: any): MetadataEntryDTO {
    return MetadataEntryDTOFromJSONTyped(json, false);
}

export function MetadataEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataEntryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'compositeHash': json['compositeHash'],
        'sourceAddress': json['sourceAddress'],
        'targetAddress': json['targetAddress'],
        'scopedMetadataKey': json['scopedMetadataKey'],
        'targetId': json['targetId'] == null ? undefined : MetadataEntryDTOTargetIdFromJSON(json['targetId']),
        'metadataType': MetadataTypeEnumFromJSON(json['metadataType']),
        'valueSize': json['valueSize'],
        'value': json['value'],
    };
}

export function MetadataEntryDTOToJSON(json: any): MetadataEntryDTO {
    return MetadataEntryDTOToJSONTyped(json, false);
}

export function MetadataEntryDTOToJSONTyped(value?: MetadataEntryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'compositeHash': value['compositeHash'],
        'sourceAddress': value['sourceAddress'],
        'targetAddress': value['targetAddress'],
        'scopedMetadataKey': value['scopedMetadataKey'],
        'targetId': MetadataEntryDTOTargetIdToJSON(value['targetId']),
        'metadataType': MetadataTypeEnumToJSON(value['metadataType']),
        'valueSize': value['valueSize'],
        'value': value['value'],
    };
}

