/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Comparison operator used to evaluate a mosaic global restriction rule.
 * - `0` (`NONE`) - Uninitialized value indicating no restriction.
 * - `1` (`EQ`) - Allow if the compared value is equal to the restriction value.
 * - `2` (`NE`) - Allow if the compared value is not equal to the restriction value.
 * - `3` (`LT`) - Allow if the compared value is less than the restriction value.
 * - `4` (`LE`) - Allow if the compared value is less than or equal to the restriction value.
 * - `5` (`GT`) - Allow if the compared value is greater than the restriction value.
 * - `6` (`GE`) - Allow if the compared value is greater than or equal to the restriction value.
 * 
 * @export
 */
export const MosaicRestrictionTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type MosaicRestrictionTypeEnum = typeof MosaicRestrictionTypeEnum[keyof typeof MosaicRestrictionTypeEnum];


export function instanceOfMosaicRestrictionTypeEnum(value: any): boolean {
    for (const key in MosaicRestrictionTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(MosaicRestrictionTypeEnum, key)) {
            if (MosaicRestrictionTypeEnum[key as keyof typeof MosaicRestrictionTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MosaicRestrictionTypeEnumFromJSON(json: any): MosaicRestrictionTypeEnum {
    return MosaicRestrictionTypeEnumFromJSONTyped(json, false);
}

export function MosaicRestrictionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicRestrictionTypeEnum {
    return json as MosaicRestrictionTypeEnum;
}

export function MosaicRestrictionTypeEnumToJSON(value?: MosaicRestrictionTypeEnum | null): any {
    return value as any;
}

export function MosaicRestrictionTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MosaicRestrictionTypeEnum {
    return value as MosaicRestrictionTypeEnum;
}

