/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';

/**
 * Transaction to set a restriction rule to an address.
 * @export
 * @interface MosaicAddressRestrictionTransactionDTO
 */
export interface MosaicAddressRestrictionTransactionDTO {
    /**
     * Unsigned 32-bit integer.
     * Represented as integer since it fits in JSON number precision.
     * 
     * @type {number}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    size: number;
    /**
     * 64-byte Ed25519 signature (128 hex characters). Generated by the signer using their private key
     * over the serialized entity payload. Can be verified with the signer's public key (`signerPublicKey`).
     * Used for blocks, transactions, and cosignatures.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    signature: string;
    /**
     * 256-bit public key encoded as a hexadecimal string (64 hex characters).
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version. Indicates the schema variant for serialization and validation.
     * @type {number}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    version: number;
    /**
     * Network type (mainnet or testnet). Ensures the entity targets the correct network.
     * @type {NetworkTypeEnum}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * Entity type identifier (e.g. transaction type code, block type). Determines the entity schema.
     * @type {number}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    type: number;
    /**
     * Absolute amount expressed in the mosaic's smallest (atomic) unit, with no decimal point.
     * For example, an amount of `123456789` for a mosaic with divisibility 6 represents
     * `123.456789` whole units. Encoded as a string to preserve precision, since the value
     * is an unsigned 64-bit integer.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    maxFee: string;
    /**
     * Network timestamp in **milliseconds** since the creation of the nemesis (first) block.
     * Used for block timestamps, transaction deadlines, and time synchronization.
     * 
     * **Finding the nemesis block time:** The `epochAdjustment` field returned by the
     * [`/network/properties`] endpoint gives the nemesis block creation time in seconds since the
     * [UNIX epoch](https://en.wikipedia.org/wiki/Unix_time). For Symbol MAINNET this is
     * always `1615853185` (15 March 2021, 00:06:25 UTC).
     * 
     * **Converting to real time:** Add this timestamp (ms) to `epochAdjustment × 1000` (ms), then use standard date functions.
     * Note: `epochAdjustment` may be returned as a string like `"1615853185s"`; use the numeric part.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    deadline: string;
    /**
     * Unresolved mosaic identifier.
     * If the most significant bit of byte 0 is set, the value contains a namespace ID alias
     * instead of a concrete mosaic ID.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    mosaicId: string;
    /**
     * Restriction key represented as a 64-bit hexadecimal value.
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    restrictionKey: string;
    /**
     * Unsigned 64-bit value associated with a mosaic restriction key, represented as a decimal string.
     * For address restrictions, it is the value assigned to the target address;
     * for global restrictions, it is the threshold evaluated with the restriction type.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    previousRestrictionValue: string;
    /**
     * Unsigned 64-bit value associated with a mosaic restriction key, represented as a decimal string.
     * For address restrictions, it is the value assigned to the target address;
     * for global restrictions, it is the threshold evaluated with the restriction type.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    newRestrictionValue: string;
    /**
     * Unresolved address encoded as a 48-character hexadecimal string (24 bytes).
     * If bit 0 of byte 0 is not set, the value represents a regular address.
     * Otherwise, it represents a namespace ID alias encoded as an unresolved address.
     * 
     * @type {string}
     * @memberof MosaicAddressRestrictionTransactionDTO
     */
    targetAddress: string;
}



/**
 * Check if a given object implements the MosaicAddressRestrictionTransactionDTO interface.
 */
export function instanceOfMosaicAddressRestrictionTransactionDTO(value: Record<string, any>): value is MosaicAddressRestrictionTransactionDTO {
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
    if (!('deadline' in value) || value['deadline'] === undefined) return false;
    if (!('mosaicId' in value) || value['mosaicId'] === undefined) return false;
    if (!('restrictionKey' in value) || value['restrictionKey'] === undefined) return false;
    if (!('previousRestrictionValue' in value) || value['previousRestrictionValue'] === undefined) return false;
    if (!('newRestrictionValue' in value) || value['newRestrictionValue'] === undefined) return false;
    if (!('targetAddress' in value) || value['targetAddress'] === undefined) return false;
    return true;
}

export function MosaicAddressRestrictionTransactionDTOFromJSON(json: any): MosaicAddressRestrictionTransactionDTO {
    return MosaicAddressRestrictionTransactionDTOFromJSONTyped(json, false);
}

export function MosaicAddressRestrictionTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicAddressRestrictionTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'],
        'signature': json['signature'],
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
        'mosaicId': json['mosaicId'],
        'restrictionKey': json['restrictionKey'],
        'previousRestrictionValue': json['previousRestrictionValue'],
        'newRestrictionValue': json['newRestrictionValue'],
        'targetAddress': json['targetAddress'],
    };
}

export function MosaicAddressRestrictionTransactionDTOToJSON(json: any): MosaicAddressRestrictionTransactionDTO {
    return MosaicAddressRestrictionTransactionDTOToJSONTyped(json, false);
}

export function MosaicAddressRestrictionTransactionDTOToJSONTyped(value?: MosaicAddressRestrictionTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'signature': value['signature'],
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'maxFee': value['maxFee'],
        'deadline': value['deadline'],
        'mosaicId': value['mosaicId'],
        'restrictionKey': value['restrictionKey'],
        'previousRestrictionValue': value['previousRestrictionValue'],
        'newRestrictionValue': value['newRestrictionValue'],
        'targetAddress': value['targetAddress'],
    };
}

