/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - 0 - Mosaic address restriction.
 * - 1 - Mosaic global restriction.
 * 
 * @export
 */
export const MosaicRestrictionEntryTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type MosaicRestrictionEntryTypeEnum = typeof MosaicRestrictionEntryTypeEnum[keyof typeof MosaicRestrictionEntryTypeEnum];


export function instanceOfMosaicRestrictionEntryTypeEnum(value: any): boolean {
    for (const key in MosaicRestrictionEntryTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(MosaicRestrictionEntryTypeEnum, key)) {
            if (MosaicRestrictionEntryTypeEnum[key as keyof typeof MosaicRestrictionEntryTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MosaicRestrictionEntryTypeEnumFromJSON(json: any): MosaicRestrictionEntryTypeEnum {
    return MosaicRestrictionEntryTypeEnumFromJSONTyped(json, false);
}

export function MosaicRestrictionEntryTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicRestrictionEntryTypeEnum {
    return json as MosaicRestrictionEntryTypeEnum;
}

export function MosaicRestrictionEntryTypeEnumToJSON(value?: MosaicRestrictionEntryTypeEnum | null): any {
    return value as any;
}

export function MosaicRestrictionEntryTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MosaicRestrictionEntryTypeEnum {
    return value as MosaicRestrictionEntryTypeEnum;
}

