/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MosaicGlobalRestrictionDTO } from './MosaicGlobalRestrictionDTO';
import {
    MosaicGlobalRestrictionDTOFromJSON,
    MosaicGlobalRestrictionDTOFromJSONTyped,
    MosaicGlobalRestrictionDTOToJSON,
    MosaicGlobalRestrictionDTOToJSONTyped,
} from './MosaicGlobalRestrictionDTO';
import type { MosaicAddressRestrictionDTO } from './MosaicAddressRestrictionDTO';
import {
    MosaicAddressRestrictionDTOFromJSON,
    MosaicAddressRestrictionDTOFromJSONTyped,
    MosaicAddressRestrictionDTOToJSON,
    MosaicAddressRestrictionDTOToJSONTyped,
} from './MosaicAddressRestrictionDTO';
import type { MosaicGlobalRestrictionEntryWrapperDTO } from './MosaicGlobalRestrictionEntryWrapperDTO';
import {
    MosaicGlobalRestrictionEntryWrapperDTOFromJSON,
    MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped,
    MosaicGlobalRestrictionEntryWrapperDTOToJSON,
    MosaicGlobalRestrictionEntryWrapperDTOToJSONTyped,
} from './MosaicGlobalRestrictionEntryWrapperDTO';

/**
 * Wrapper object containing one mosaic restriction entry, either a global restriction or an address restriction.
 * @export
 * @interface MosaicRestrictionDTO
 */
export interface MosaicRestrictionDTO {
    /**
     * Unique identifier of the object in the node's database (MongoDB ObjectId).
     * Used as the `offset` parameter value for cursor-based pagination.
     * 
     * @type {string}
     * @memberof MosaicRestrictionDTO
     */
    id: string;
    /**
     * 
     * @type {MosaicGlobalRestrictionEntryWrapperDTO}
     * @memberof MosaicRestrictionDTO
     */
    mosaicRestrictionEntry: MosaicGlobalRestrictionEntryWrapperDTO;
}

/**
 * Check if a given object implements the MosaicRestrictionDTO interface.
 */
export function instanceOfMosaicRestrictionDTO(value: Record<string, any>): value is MosaicRestrictionDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mosaicRestrictionEntry' in value) || value['mosaicRestrictionEntry'] === undefined) return false;
    return true;
}

export function MosaicRestrictionDTOFromJSON(json: any): MosaicRestrictionDTO {
    return MosaicRestrictionDTOFromJSONTyped(json, false);
}

export function MosaicRestrictionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicRestrictionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mosaicRestrictionEntry': MosaicGlobalRestrictionEntryWrapperDTOFromJSON(json['mosaicRestrictionEntry']),
    };
}

export function MosaicRestrictionDTOToJSON(json: any): MosaicRestrictionDTO {
    return MosaicRestrictionDTOToJSONTyped(json, false);
}

export function MosaicRestrictionDTOToJSONTyped(value?: MosaicRestrictionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mosaicRestrictionEntry': MosaicGlobalRestrictionEntryWrapperDTOToJSON(value['mosaicRestrictionEntry']),
    };
}

