/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AliasActionEnum } from './AliasActionEnum';
import {
    AliasActionEnumFromJSON,
    AliasActionEnumFromJSONTyped,
    AliasActionEnumToJSON,
    AliasActionEnumToJSONTyped,
} from './AliasActionEnum';

/**
 * 
 * @export
 * @interface MosaicAliasTransactionBodyDTO
 */
export interface MosaicAliasTransactionBodyDTO {
    /**
     * Namespace identifier.
     * @type {string}
     * @memberof MosaicAliasTransactionBodyDTO
     */
    namespaceId: string;
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof MosaicAliasTransactionBodyDTO
     */
    mosaicId: string;
    /**
     * 
     * @type {AliasActionEnum}
     * @memberof MosaicAliasTransactionBodyDTO
     */
    aliasAction: AliasActionEnum;
}



/**
 * Check if a given object implements the MosaicAliasTransactionBodyDTO interface.
 */
export function instanceOfMosaicAliasTransactionBodyDTO(value: Record<string, any>): value is MosaicAliasTransactionBodyDTO {
    if (!('namespaceId' in value) || value['namespaceId'] === undefined) return false;
    if (!('mosaicId' in value) || value['mosaicId'] === undefined) return false;
    if (!('aliasAction' in value) || value['aliasAction'] === undefined) return false;
    return true;
}

export function MosaicAliasTransactionBodyDTOFromJSON(json: any): MosaicAliasTransactionBodyDTO {
    return MosaicAliasTransactionBodyDTOFromJSONTyped(json, false);
}

export function MosaicAliasTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicAliasTransactionBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'namespaceId': json['namespaceId'],
        'mosaicId': json['mosaicId'],
        'aliasAction': AliasActionEnumFromJSON(json['aliasAction']),
    };
}

export function MosaicAliasTransactionBodyDTOToJSON(json: any): MosaicAliasTransactionBodyDTO {
    return MosaicAliasTransactionBodyDTOToJSONTyped(json, false);
}

export function MosaicAliasTransactionBodyDTOToJSONTyped(value?: MosaicAliasTransactionBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespaceId': value['namespaceId'],
        'mosaicId': value['mosaicId'],
        'aliasAction': AliasActionEnumToJSON(value['aliasAction']),
    };
}

