/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mosaic supply change action:
 * - `0`: Decrease the mosaic supply.
 * - `1`: Increase the mosaic supply.
 * 
 * @export
 */
export const MosaicSupplyChangeActionEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type MosaicSupplyChangeActionEnum = typeof MosaicSupplyChangeActionEnum[keyof typeof MosaicSupplyChangeActionEnum];


export function instanceOfMosaicSupplyChangeActionEnum(value: any): boolean {
    for (const key in MosaicSupplyChangeActionEnum) {
        if (Object.prototype.hasOwnProperty.call(MosaicSupplyChangeActionEnum, key)) {
            if (MosaicSupplyChangeActionEnum[key as keyof typeof MosaicSupplyChangeActionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MosaicSupplyChangeActionEnumFromJSON(json: any): MosaicSupplyChangeActionEnum {
    return MosaicSupplyChangeActionEnumFromJSONTyped(json, false);
}

export function MosaicSupplyChangeActionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicSupplyChangeActionEnum {
    return json as MosaicSupplyChangeActionEnum;
}

export function MosaicSupplyChangeActionEnumToJSON(value?: MosaicSupplyChangeActionEnum | null): any {
    return value as any;
}

export function MosaicSupplyChangeActionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MosaicSupplyChangeActionEnum {
    return value as MosaicSupplyChangeActionEnum;
}

