/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MosaicAddressRestrictionEntryDTO
 */
export interface MosaicAddressRestrictionEntryDTO {
    /**
     * Restriction key.
     * @type {string}
     * @memberof MosaicAddressRestrictionEntryDTO
     */
    key: string;
    /**
     * Restriction value.
     * @type {string}
     * @memberof MosaicAddressRestrictionEntryDTO
     */
    value: string;
}

/**
 * Check if a given object implements the MosaicAddressRestrictionEntryDTO interface.
 */
export function instanceOfMosaicAddressRestrictionEntryDTO(value: Record<string, any>): value is MosaicAddressRestrictionEntryDTO {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MosaicAddressRestrictionEntryDTOFromJSON(json: any): MosaicAddressRestrictionEntryDTO {
    return MosaicAddressRestrictionEntryDTOFromJSONTyped(json, false);
}

export function MosaicAddressRestrictionEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicAddressRestrictionEntryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function MosaicAddressRestrictionEntryDTOToJSON(json: any): MosaicAddressRestrictionEntryDTO {
    return MosaicAddressRestrictionEntryDTOToJSONTyped(json, false);
}

export function MosaicAddressRestrictionEntryDTOToJSONTyped(value?: MosaicAddressRestrictionEntryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

