/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Current multisig state of an account.
 * @export
 * @interface MultisigDTO
 */
export interface MultisigDTO {
    /**
     * Version of the on-chain state serialization format. Incremented when the storage
     * schema of the entity changes (e.g. new fields are added), allowing the node to
     * deserialize entries written under earlier formats.
     * 
     * @type {number}
     * @memberof MultisigDTO
     */
    version: number;
    /**
     * Address encoded as a 48-character hexadecimal string (24 bytes).
     * The REST API returns addresses in this format. For Base32-encoded addresses (39 chars) see `Address`.
     * 
     * @type {string}
     * @memberof MultisigDTO
     */
    accountAddress: string;
    /**
     * Unsigned 32-bit integer.
     * Represented as integer since it fits in JSON number precision.
     * 
     * @type {number}
     * @memberof MultisigDTO
     */
    minApproval: number;
    /**
     * Unsigned 32-bit integer.
     * Represented as integer since it fits in JSON number precision.
     * 
     * @type {number}
     * @memberof MultisigDTO
     */
    minRemoval: number;
    /**
     * Direct cosignatory addresses that manage this multisig account.
     * @type {Array<string>}
     * @memberof MultisigDTO
     */
    cosignatoryAddresses: Array<string>;
    /**
     * Multisig account addresses where this account acts as a cosignatory.
     * @type {Array<string>}
     * @memberof MultisigDTO
     */
    multisigAddresses: Array<string>;
}

/**
 * Check if a given object implements the MultisigDTO interface.
 */
export function instanceOfMultisigDTO(value: Record<string, any>): value is MultisigDTO {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('accountAddress' in value) || value['accountAddress'] === undefined) return false;
    if (!('minApproval' in value) || value['minApproval'] === undefined) return false;
    if (!('minRemoval' in value) || value['minRemoval'] === undefined) return false;
    if (!('cosignatoryAddresses' in value) || value['cosignatoryAddresses'] === undefined) return false;
    if (!('multisigAddresses' in value) || value['multisigAddresses'] === undefined) return false;
    return true;
}

export function MultisigDTOFromJSON(json: any): MultisigDTO {
    return MultisigDTOFromJSONTyped(json, false);
}

export function MultisigDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultisigDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'accountAddress': json['accountAddress'],
        'minApproval': json['minApproval'],
        'minRemoval': json['minRemoval'],
        'cosignatoryAddresses': json['cosignatoryAddresses'],
        'multisigAddresses': json['multisigAddresses'],
    };
}

export function MultisigDTOToJSON(json: any): MultisigDTO {
    return MultisigDTOToJSONTyped(json, false);
}

export function MultisigDTOToJSONTyped(value?: MultisigDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'accountAddress': value['accountAddress'],
        'minApproval': value['minApproval'],
        'minRemoval': value['minRemoval'],
        'cosignatoryAddresses': value['cosignatoryAddresses'],
        'multisigAddresses': value['multisigAddresses'],
    };
}

