/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultisigAccountModificationTransactionBodyDTO
 */
export interface MultisigAccountModificationTransactionBodyDTO {
    /**
     * Number of signatures needed to remove a cosignatory.
     * If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories.
     * 
     * @type {number}
     * @memberof MultisigAccountModificationTransactionBodyDTO
     */
    minRemovalDelta: number;
    /**
     * Number of signatures needed to approve a transaction.
     * If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories.
     * 
     * @type {number}
     * @memberof MultisigAccountModificationTransactionBodyDTO
     */
    minApprovalDelta: number;
    /**
     * Array of cosignatory accounts to add.
     * @type {Array<string>}
     * @memberof MultisigAccountModificationTransactionBodyDTO
     */
    addressAdditions: Array<string>;
    /**
     * Array of cosignatory accounts to delete.
     * @type {Array<string>}
     * @memberof MultisigAccountModificationTransactionBodyDTO
     */
    addressDeletions: Array<string>;
}

/**
 * Check if a given object implements the MultisigAccountModificationTransactionBodyDTO interface.
 */
export function instanceOfMultisigAccountModificationTransactionBodyDTO(value: Record<string, any>): value is MultisigAccountModificationTransactionBodyDTO {
    if (!('minRemovalDelta' in value) || value['minRemovalDelta'] === undefined) return false;
    if (!('minApprovalDelta' in value) || value['minApprovalDelta'] === undefined) return false;
    if (!('addressAdditions' in value) || value['addressAdditions'] === undefined) return false;
    if (!('addressDeletions' in value) || value['addressDeletions'] === undefined) return false;
    return true;
}

export function MultisigAccountModificationTransactionBodyDTOFromJSON(json: any): MultisigAccountModificationTransactionBodyDTO {
    return MultisigAccountModificationTransactionBodyDTOFromJSONTyped(json, false);
}

export function MultisigAccountModificationTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultisigAccountModificationTransactionBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'minRemovalDelta': json['minRemovalDelta'],
        'minApprovalDelta': json['minApprovalDelta'],
        'addressAdditions': json['addressAdditions'],
        'addressDeletions': json['addressDeletions'],
    };
}

export function MultisigAccountModificationTransactionBodyDTOToJSON(json: any): MultisigAccountModificationTransactionBodyDTO {
    return MultisigAccountModificationTransactionBodyDTOToJSONTyped(json, false);
}

export function MultisigAccountModificationTransactionBodyDTOToJSONTyped(value?: MultisigAccountModificationTransactionBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minRemovalDelta': value['minRemovalDelta'],
        'minApprovalDelta': value['minApprovalDelta'],
        'addressAdditions': value['addressAdditions'],
        'addressDeletions': value['addressDeletions'],
    };
}

