/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
import {
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum';

/**
 * Transaction that converts a regular account into a multisig account or modifies an existing
 * multisig account's thresholds and cosignatory set.
 * 
 * @export
 * @interface MultisigAccountModificationTransactionDTO
 */
export interface MultisigAccountModificationTransactionDTO {
    /**
     * Unsigned 32-bit integer.
     * Represented as integer since it fits in JSON number precision.
     * 
     * @type {number}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    size: number;
    /**
     * 64-byte Ed25519 signature (128 hex characters). Generated by the signer using their private key
     * over the serialized entity payload. Can be verified with the signer's public key (`signerPublicKey`).
     * Used for blocks, transactions, and cosignatures.
     * 
     * @type {string}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    signature: string;
    /**
     * 256-bit public key encoded as a hexadecimal string (64 hex characters).
     * @type {string}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version. Indicates the schema variant for serialization and validation.
     * @type {number}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    version: number;
    /**
     * Network type (mainnet or testnet). Ensures the entity targets the correct network.
     * @type {NetworkTypeEnum}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * Entity type identifier (e.g. transaction type code, block type). Determines the entity schema.
     * @type {number}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    type: number;
    /**
     * Absolute amount expressed in the mosaic's smallest (atomic) unit, with no decimal point.
     * For example, an amount of `123456789` for a mosaic with divisibility 6 represents
     * `123.456789` whole units. Encoded as a string to preserve precision, since the value
     * is an unsigned 64-bit integer.
     * 
     * @type {string}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    maxFee: string;
    /**
     * Network timestamp in **milliseconds** since the creation of the nemesis (first) block.
     * Used for block timestamps, transaction deadlines, and time synchronization.
     * 
     * **Finding the nemesis block time:** The `epochAdjustment` field returned by the
     * [`/network/properties`] endpoint gives the nemesis block creation time in seconds since the
     * [UNIX epoch](https://en.wikipedia.org/wiki/Unix_time). For Symbol MAINNET this is
     * always `1615853185` (15 March 2021, 00:06:25 UTC).
     * 
     * **Converting to real time:** Add this timestamp (ms) to `epochAdjustment × 1000` (ms), then use standard date functions.
     * Note: `epochAdjustment` may be returned as a string like `"1615853185s"`; use the numeric part.
     * 
     * @type {string}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    deadline: string;
    /**
     * Relative change applied to the minimum number of cosignatory approvals required to remove a
     * cosignatory. When converting a regular account into a multisig account, the initial value is
     * derived from this delta because the previous threshold is zero.
     * 
     * @type {number}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    minRemovalDelta: number;
    /**
     * Relative change applied to the minimum number of cosignatory approvals required to approve a
     * transaction. When converting a regular account into a multisig account, the initial value is
     * derived from this delta because the previous threshold is zero.
     * 
     * @type {number}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    minApprovalDelta: number;
    /**
     * Cosignatory addresses to add to the multisig account.
     * Newly added cosignatories must opt in by cosigning the aggregate transaction.
     * 
     * @type {Array<string>}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    addressAdditions: Array<string>;
    /**
     * Cosignatory addresses to remove from the multisig account.
     * @type {Array<string>}
     * @memberof MultisigAccountModificationTransactionDTO
     */
    addressDeletions: Array<string>;
}



/**
 * Check if a given object implements the MultisigAccountModificationTransactionDTO interface.
 */
export function instanceOfMultisigAccountModificationTransactionDTO(value: Record<string, any>): value is MultisigAccountModificationTransactionDTO {
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
    if (!('deadline' in value) || value['deadline'] === undefined) return false;
    if (!('minRemovalDelta' in value) || value['minRemovalDelta'] === undefined) return false;
    if (!('minApprovalDelta' in value) || value['minApprovalDelta'] === undefined) return false;
    if (!('addressAdditions' in value) || value['addressAdditions'] === undefined) return false;
    if (!('addressDeletions' in value) || value['addressDeletions'] === undefined) return false;
    return true;
}

export function MultisigAccountModificationTransactionDTOFromJSON(json: any): MultisigAccountModificationTransactionDTO {
    return MultisigAccountModificationTransactionDTOFromJSONTyped(json, false);
}

export function MultisigAccountModificationTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultisigAccountModificationTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'],
        'signature': json['signature'],
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': NetworkTypeEnumFromJSON(json['network']),
        'type': json['type'],
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
        'minRemovalDelta': json['minRemovalDelta'],
        'minApprovalDelta': json['minApprovalDelta'],
        'addressAdditions': json['addressAdditions'],
        'addressDeletions': json['addressDeletions'],
    };
}

export function MultisigAccountModificationTransactionDTOToJSON(json: any): MultisigAccountModificationTransactionDTO {
    return MultisigAccountModificationTransactionDTOToJSONTyped(json, false);
}

export function MultisigAccountModificationTransactionDTOToJSONTyped(value?: MultisigAccountModificationTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'signature': value['signature'],
        'signerPublicKey': value['signerPublicKey'],
        'version': value['version'],
        'network': NetworkTypeEnumToJSON(value['network']),
        'type': value['type'],
        'maxFee': value['maxFee'],
        'deadline': value['deadline'],
        'minRemovalDelta': value['minRemovalDelta'],
        'minApprovalDelta': value['minApprovalDelta'],
        'addressAdditions': value['addressAdditions'],
        'addressDeletions': value['addressDeletions'],
    };
}

