/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NamespaceDTO,
    NamespaceDTOFromJSON,
    NamespaceDTOFromJSONTyped,
    NamespaceDTOToJSON,
} from './NamespaceDTO';
import {
    NamespaceMetaDTO,
    NamespaceMetaDTOFromJSON,
    NamespaceMetaDTOFromJSONTyped,
    NamespaceMetaDTOToJSON,
} from './NamespaceMetaDTO';

/**
 * 
 * @export
 * @interface NamespaceInfoDTO
 */
export interface NamespaceInfoDTO {
    /**
     * Internal resource identifier.
     * @type {string}
     * @memberof NamespaceInfoDTO
     */
    id: string;
    /**
     * 
     * @type {NamespaceMetaDTO}
     * @memberof NamespaceInfoDTO
     */
    meta: NamespaceMetaDTO;
    /**
     * 
     * @type {NamespaceDTO}
     * @memberof NamespaceInfoDTO
     */
    namespace: NamespaceDTO;
}

export function NamespaceInfoDTOFromJSON(json: any): NamespaceInfoDTO {
    return NamespaceInfoDTOFromJSONTyped(json, false);
}

export function NamespaceInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'meta': NamespaceMetaDTOFromJSON(json['meta']),
        'namespace': NamespaceDTOFromJSON(json['namespace']),
    };
}

export function NamespaceInfoDTOToJSON(value?: NamespaceInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'meta': NamespaceMetaDTOToJSON(value.meta),
        'namespace': NamespaceDTOToJSON(value.namespace),
    };
}

