/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamespaceMetaDTO
 */
export interface NamespaceMetaDTO {
    /**
     * If true, the namespace is active.
     * @type {boolean}
     * @memberof NamespaceMetaDTO
     */
    active: boolean;
    /**
     * 
     * @type {number}
     * @memberof NamespaceMetaDTO
     */
    index: number;
}

export function NamespaceMetaDTOFromJSON(json: any): NamespaceMetaDTO {
    return NamespaceMetaDTOFromJSONTyped(json, false);
}

export function NamespaceMetaDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceMetaDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': json['active'],
        'index': json['index'],
    };
}

export function NamespaceMetaDTOToJSON(value?: NamespaceMetaDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'index': value.index,
    };
}

