/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata about the namespace entry.
 * Includes whether the namespace is currently active and its internal ordering index.
 * 
 * @export
 * @interface NamespaceMetaDTO
 */
export interface NamespaceMetaDTO {
    /**
     * Indicates whether the namespace is currently active at the chain height used to serve the request.
     * @type {boolean}
     * @memberof NamespaceMetaDTO
     */
    active: boolean;
    /**
     * Internal namespace index used by the backend and Mongo storage to identify and order historical
     * namespace entries. This value is returned for informational purposes only.
     * API clients should not use it as a pagination cursor; use the standard pagination query parameters (`pageSize`,
     * `pageNumber`, `offset`, `order`) instead.
     * 
     * @type {number}
     * @memberof NamespaceMetaDTO
     */
    index: number;
}

/**
 * Check if a given object implements the NamespaceMetaDTO interface.
 */
export function instanceOfNamespaceMetaDTO(value: Record<string, any>): value is NamespaceMetaDTO {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function NamespaceMetaDTOFromJSON(json: any): NamespaceMetaDTO {
    return NamespaceMetaDTOFromJSONTyped(json, false);
}

export function NamespaceMetaDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceMetaDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'index': json['index'],
    };
}

export function NamespaceMetaDTOToJSON(json: any): NamespaceMetaDTO {
    return NamespaceMetaDTOToJSONTyped(json, false);
}

export function NamespaceMetaDTOToJSONTyped(value?: NamespaceMetaDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'index': value['index'],
    };
}

