/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Node equality strategy. Defines if the identifier for the node must be its public key or host.
 * 
 * @export
 */
export const NodeIdentityEqualityStrategy = {
    Host: 'host',
    PublicKey: 'public-key'
} as const;
export type NodeIdentityEqualityStrategy = typeof NodeIdentityEqualityStrategy[keyof typeof NodeIdentityEqualityStrategy];


export function instanceOfNodeIdentityEqualityStrategy(value: any): boolean {
    for (const key in NodeIdentityEqualityStrategy) {
        if (Object.prototype.hasOwnProperty.call(NodeIdentityEqualityStrategy, key)) {
            if (NodeIdentityEqualityStrategy[key as keyof typeof NodeIdentityEqualityStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NodeIdentityEqualityStrategyFromJSON(json: any): NodeIdentityEqualityStrategy {
    return NodeIdentityEqualityStrategyFromJSONTyped(json, false);
}

export function NodeIdentityEqualityStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeIdentityEqualityStrategy {
    return json as NodeIdentityEqualityStrategy;
}

export function NodeIdentityEqualityStrategyToJSON(value?: NodeIdentityEqualityStrategy | null): any {
    return value as any;
}

export function NodeIdentityEqualityStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): NodeIdentityEqualityStrategy {
    return value as NodeIdentityEqualityStrategy;
}

