/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeHealthDTO } from './NodeHealthDTO';
import {
    NodeHealthDTOFromJSON,
    NodeHealthDTOFromJSONTyped,
    NodeHealthDTOToJSON,
    NodeHealthDTOToJSONTyped,
} from './NodeHealthDTO';

/**
 * 
 * @export
 * @interface NodeHealthInfoDTO
 */
export interface NodeHealthInfoDTO {
    /**
     * 
     * @type {NodeHealthDTO}
     * @memberof NodeHealthInfoDTO
     */
    status: NodeHealthDTO;
}

/**
 * Check if a given object implements the NodeHealthInfoDTO interface.
 */
export function instanceOfNodeHealthInfoDTO(value: Record<string, any>): value is NodeHealthInfoDTO {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NodeHealthInfoDTOFromJSON(json: any): NodeHealthInfoDTO {
    return NodeHealthInfoDTOFromJSONTyped(json, false);
}

export function NodeHealthInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeHealthInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'status': NodeHealthDTOFromJSON(json['status']),
    };
}

export function NodeHealthInfoDTOToJSON(json: any): NodeHealthInfoDTO {
    return NodeHealthInfoDTOToJSONTyped(json, false);
}

export function NodeHealthInfoDTOToJSONTyped(value?: NodeHealthInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': NodeHealthDTOToJSON(value['status']),
    };
}

