/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeKeyLinkNetworkPropertiesDTO
 */
export interface NodeKeyLinkNetworkPropertiesDTO {
    /**
     * to trigger plugin load
     * @type {string}
     * @memberof NodeKeyLinkNetworkPropertiesDTO
     */
    dummy?: string;
}

/**
 * Check if a given object implements the NodeKeyLinkNetworkPropertiesDTO interface.
 */
export function instanceOfNodeKeyLinkNetworkPropertiesDTO(value: Record<string, any>): value is NodeKeyLinkNetworkPropertiesDTO {
    return true;
}

export function NodeKeyLinkNetworkPropertiesDTOFromJSON(json: any): NodeKeyLinkNetworkPropertiesDTO {
    return NodeKeyLinkNetworkPropertiesDTOFromJSONTyped(json, false);
}

export function NodeKeyLinkNetworkPropertiesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeKeyLinkNetworkPropertiesDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'dummy': json['dummy'] == null ? undefined : json['dummy'],
    };
}

export function NodeKeyLinkNetworkPropertiesDTOToJSON(json: any): NodeKeyLinkNetworkPropertiesDTO {
    return NodeKeyLinkNetworkPropertiesDTOToJSONTyped(json, false);
}

export function NodeKeyLinkNetworkPropertiesDTOToJSONTyped(value?: NodeKeyLinkNetworkPropertiesDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dummy': value['dummy'],
    };
}

