/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParentPublicKeySignaturePair
 */
export interface ParentPublicKeySignaturePair {
    /**
     * Public key.
     * @type {string}
     * @memberof ParentPublicKeySignaturePair
     */
    parentPublicKey: string;
    /**
     * Entity's signature generated by the signer.
     * @type {string}
     * @memberof ParentPublicKeySignaturePair
     */
    signature: string;
}

/**
 * Check if a given object implements the ParentPublicKeySignaturePair interface.
 */
export function instanceOfParentPublicKeySignaturePair(value: Record<string, any>): value is ParentPublicKeySignaturePair {
    if (!('parentPublicKey' in value) || value['parentPublicKey'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function ParentPublicKeySignaturePairFromJSON(json: any): ParentPublicKeySignaturePair {
    return ParentPublicKeySignaturePairFromJSONTyped(json, false);
}

export function ParentPublicKeySignaturePairFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentPublicKeySignaturePair {
    if (json == null) {
        return json;
    }
    return {
        
        'parentPublicKey': json['parentPublicKey'],
        'signature': json['signature'],
    };
}

export function ParentPublicKeySignaturePairToJSON(json: any): ParentPublicKeySignaturePair {
    return ParentPublicKeySignaturePairToJSONTyped(json, false);
}

export function ParentPublicKeySignaturePairToJSONTyped(value?: ParentPublicKeySignaturePair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentPublicKey': value['parentPublicKey'],
        'signature': value['signature'],
    };
}

