/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Pagination,
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import {
    ResolutionStatementInfoDTO,
    ResolutionStatementInfoDTOFromJSON,
    ResolutionStatementInfoDTOFromJSONTyped,
    ResolutionStatementInfoDTOToJSON,
} from './ResolutionStatementInfoDTO';

/**
 * 
 * @export
 * @interface ResolutionStatementPage
 */
export interface ResolutionStatementPage {
    /**
     * Array of transaction address resolution statements.
     * @type {Array<ResolutionStatementInfoDTO>}
     * @memberof ResolutionStatementPage
     */
    data: Array<ResolutionStatementInfoDTO>;
    /**
     * 
     * @type {Pagination}
     * @memberof ResolutionStatementPage
     */
    pagination: Pagination;
}

export function ResolutionStatementPageFromJSON(json: any): ResolutionStatementPage {
    return ResolutionStatementPageFromJSONTyped(json, false);
}

export function ResolutionStatementPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolutionStatementPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResolutionStatementInfoDTOFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function ResolutionStatementPageToJSON(value?: ResolutionStatementPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResolutionStatementInfoDTOToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

