/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResolutionEntryDTOResolved
 */
export interface ResolutionEntryDTOResolved {
}

/**
 * Check if a given object implements the ResolutionEntryDTOResolved interface.
 */
export function instanceOfResolutionEntryDTOResolved(value: Record<string, any>): value is ResolutionEntryDTOResolved {
    return true;
}

export function ResolutionEntryDTOResolvedFromJSON(json: any): ResolutionEntryDTOResolved {
    return ResolutionEntryDTOResolvedFromJSONTyped(json, false);
}

export function ResolutionEntryDTOResolvedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolutionEntryDTOResolved {
    return json;
}

export function ResolutionEntryDTOResolvedToJSON(json: any): ResolutionEntryDTOResolved {
    return ResolutionEntryDTOResolvedToJSONTyped(json, false);
}

export function ResolutionEntryDTOResolvedToJSONTyped(value?: ResolutionEntryDTOResolved | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

