/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Transaction that triggered the receipt.
 * @export
 * @interface SourceDTO
 */
export interface SourceDTO {
    /**
     * A number that allows uint 32 values.
     * @type {number}
     * @memberof SourceDTO
     */
    primaryId: number;
    /**
     * A number that allows uint 32 values.
     * @type {number}
     * @memberof SourceDTO
     */
    secondaryId: number;
}

/**
 * Check if a given object implements the SourceDTO interface.
 */
export function instanceOfSourceDTO(value: Record<string, any>): value is SourceDTO {
    if (!('primaryId' in value) || value['primaryId'] === undefined) return false;
    if (!('secondaryId' in value) || value['secondaryId'] === undefined) return false;
    return true;
}

export function SourceDTOFromJSON(json: any): SourceDTO {
    return SourceDTOFromJSONTyped(json, false);
}

export function SourceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryId': json['primaryId'],
        'secondaryId': json['secondaryId'],
    };
}

export function SourceDTOToJSON(json: any): SourceDTO {
    return SourceDTOToJSONTyped(json, false);
}

export function SourceDTOToJSONTyped(value?: SourceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primaryId': value['primaryId'],
        'secondaryId': value['secondaryId'],
    };
}

