/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Common body fields shared by all top-level transactions.
 * @export
 * @interface TransactionBodyDTO
 */
export interface TransactionBodyDTO {
    /**
     * Absolute amount expressed in the mosaic's smallest (atomic) unit, with no decimal point.
     * For example, an amount of `123456789` for a mosaic with divisibility 6 represents
     * `123.456789` whole units. Encoded as a string to preserve precision, since the value
     * is an unsigned 64-bit integer.
     * 
     * @type {string}
     * @memberof TransactionBodyDTO
     */
    maxFee: string;
    /**
     * Network timestamp in **milliseconds** since the creation of the nemesis (first) block.
     * Used for block timestamps, transaction deadlines, and time synchronization.
     * 
     * **Finding the nemesis block time:** The `epochAdjustment` field returned by the
     * [`/network/properties`] endpoint gives the nemesis block creation time in seconds since the
     * [UNIX epoch](https://en.wikipedia.org/wiki/Unix_time). For Symbol MAINNET this is
     * always `1615853185` (15 March 2021, 00:06:25 UTC).
     * 
     * **Converting to real time:** Add this timestamp (ms) to `epochAdjustment × 1000` (ms), then use standard date functions.
     * Note: `epochAdjustment` may be returned as a string like `"1615853185s"`; use the numeric part.
     * 
     * @type {string}
     * @memberof TransactionBodyDTO
     */
    deadline: string;
}

/**
 * Check if a given object implements the TransactionBodyDTO interface.
 */
export function instanceOfTransactionBodyDTO(value: Record<string, any>): value is TransactionBodyDTO {
    if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
    if (!('deadline' in value) || value['deadline'] === undefined) return false;
    return true;
}

export function TransactionBodyDTOFromJSON(json: any): TransactionBodyDTO {
    return TransactionBodyDTOFromJSONTyped(json, false);
}

export function TransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
    };
}

export function TransactionBodyDTOToJSON(json: any): TransactionBodyDTO {
    return TransactionBodyDTOToJSONTyped(json, false);
}

export function TransactionBodyDTOToJSONTyped(value?: TransactionBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxFee': value['maxFee'],
        'deadline': value['deadline'],
    };
}

