/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SourceDTO,
    SourceDTOFromJSON,
    SourceDTOFromJSONTyped,
    SourceDTOToJSON,
} from './SourceDTO';
import {
    TransactionStatementDTOReceiptsInner,
    TransactionStatementDTOReceiptsInnerFromJSON,
    TransactionStatementDTOReceiptsInnerFromJSONTyped,
    TransactionStatementDTOReceiptsInnerToJSON,
} from './TransactionStatementDTOReceiptsInner';

/**
 * 
 * @export
 * @interface TransactionStatementDTO
 */
export interface TransactionStatementDTO {
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof TransactionStatementDTO
     */
    height: string;
    /**
     * 
     * @type {SourceDTO}
     * @memberof TransactionStatementDTO
     */
    source: SourceDTO;
    /**
     * Array of receipts.
     * @type {Array<TransactionStatementDTOReceiptsInner>}
     * @memberof TransactionStatementDTO
     */
    receipts: Array<TransactionStatementDTOReceiptsInner>;
}

export function TransactionStatementDTOFromJSON(json: any): TransactionStatementDTO {
    return TransactionStatementDTOFromJSONTyped(json, false);
}

export function TransactionStatementDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatementDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': json['height'],
        'source': SourceDTOFromJSON(json['source']),
        'receipts': ((json['receipts'] as Array<any>).map(TransactionStatementDTOReceiptsInnerFromJSON)),
    };
}

export function TransactionStatementDTOToJSON(value?: TransactionStatementDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': value.height,
        'source': SourceDTOToJSON(value.source),
        'receipts': ((value.receipts as Array<any>).map(TransactionStatementDTOReceiptsInnerToJSON)),
    };
}

