/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionGroupEnum,
    TransactionGroupEnumFromJSON,
    TransactionGroupEnumFromJSONTyped,
    TransactionGroupEnumToJSON,
} from './TransactionGroupEnum';
import {
    TransactionStatusEnum,
    TransactionStatusEnumFromJSON,
    TransactionStatusEnumFromJSONTyped,
    TransactionStatusEnumToJSON,
} from './TransactionStatusEnum';

/**
 * 
 * @export
 * @interface TransactionStatusDTO
 */
export interface TransactionStatusDTO {
    /**
     * 
     * @type {TransactionGroupEnum}
     * @memberof TransactionStatusDTO
     */
    group: TransactionGroupEnum;
    /**
     * 
     * @type {TransactionStatusEnum}
     * @memberof TransactionStatusDTO
     */
    code?: TransactionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    hash: string;
    /**
     * Duration expressed in number of blocks.
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    deadline: string;
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    height?: string;
}

export function TransactionStatusDTOFromJSON(json: any): TransactionStatusDTO {
    return TransactionStatusDTOFromJSONTyped(json, false);
}

export function TransactionStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatusDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': TransactionGroupEnumFromJSON(json['group']),
        'code': !exists(json, 'code') ? undefined : TransactionStatusEnumFromJSON(json['code']),
        'hash': json['hash'],
        'deadline': json['deadline'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function TransactionStatusDTOToJSON(value?: TransactionStatusDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': TransactionGroupEnumToJSON(value.group),
        'code': TransactionStatusEnumToJSON(value.code),
        'hash': value.hash,
        'deadline': value.deadline,
        'height': value.height,
    };
}

