/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionIds
 */
export interface TransactionIds {
    /**
     * Array of transaction identifiers.
     * @type {Array<string>}
     * @memberof TransactionIds
     */
    transactionIds?: Array<string>;
}

/**
 * Check if a given object implements the TransactionIds interface.
 */
export function instanceOfTransactionIds(value: Record<string, any>): value is TransactionIds {
    return true;
}

export function TransactionIdsFromJSON(json: any): TransactionIds {
    return TransactionIdsFromJSONTyped(json, false);
}

export function TransactionIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIds {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionIds': json['transactionIds'] == null ? undefined : json['transactionIds'],
    };
}

export function TransactionIdsToJSON(json: any): TransactionIds {
    return TransactionIdsToJSONTyped(json, false);
}

export function TransactionIdsToJSONTyped(value?: TransactionIds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionIds': value['transactionIds'],
    };
}

