/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddedTransactionMetaDTO } from './EmbeddedTransactionMetaDTO';
import {
    EmbeddedTransactionMetaDTOFromJSON,
    EmbeddedTransactionMetaDTOFromJSONTyped,
    EmbeddedTransactionMetaDTOToJSON,
    EmbeddedTransactionMetaDTOToJSONTyped,
} from './EmbeddedTransactionMetaDTO';
import type { TransactionMetaDTO } from './TransactionMetaDTO';
import {
    TransactionMetaDTOFromJSON,
    TransactionMetaDTOFromJSONTyped,
    TransactionMetaDTOToJSON,
    TransactionMetaDTOToJSONTyped,
} from './TransactionMetaDTO';

/**
 * Metadata for the returned transaction entry.
 * Top-level entries use `TransactionMetaDTO`. Embedded entries use `EmbeddedTransactionMetaDTO`.
 * 
 * @export
 * @interface TransactionInfoDTOMeta
 */
export interface TransactionInfoDTOMeta {
    /**
     * Height of the block containing the referenced transaction or parent aggregate transaction.
     * Returned as a decimal string. The value is `"0"` when the transaction is not included in a
     * block yet, for example for unconfirmed transactions and partial aggregate transactions.
     * 
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    height: string;
    /**
     * 256-bit hash encoded as a 64-character hexadecimal string.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    hash: string;
    /**
     * 256-bit hash encoded as a 64-character hexadecimal string.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    merkleComponentHash: string;
    /**
     * Embedded transaction index within the parent aggregate transaction.
     * @type {number}
     * @memberof TransactionInfoDTOMeta
     */
    index: number;
    /**
     * Network timestamp in **milliseconds** since the creation of the nemesis (first) block.
     * Used for block timestamps, transaction deadlines, and time synchronization.
     * 
     * **Finding the nemesis block time:** The `epochAdjustment` field returned by the
     * [`/network/properties`] endpoint gives the nemesis block creation time in seconds since the
     * [UNIX epoch](https://en.wikipedia.org/wiki/Unix_time). For Symbol MAINNET this is
     * always `1615853185` (15 March 2021, 00:06:25 UTC).
     * 
     * **Converting to real time:** Add this timestamp (ms) to `epochAdjustment × 1000` (ms), then use standard date functions.
     * Note: `epochAdjustment` may be returned as a string like `"1615853185s"`; use the numeric part.
     * 
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    timestamp?: string;
    /**
     * Fee multiplier applied to the size of a transaction to obtain its fee, in
     * [absolute units](https://docs.symbol.dev/concepts/mosaic.html#divisibility).
     * Set by the harvester when creating a block; stored in the block header.
     * 
     * The effective fee for a transaction is:
     * 
     * `effectiveFee = transaction.size × block.feeMultiplier`
     * 
     * Node owners can configure the fee multiplier to any non-negative value (including zero).
     * For transaction senders, the median fee multiplier over recent blocks is available
     * via `/network/fees/transaction`; using `medianFeeMultiplier` or higher
     * improves chances of inclusion. See the [fees documentation](https://docs.symbol.dev/concepts/fees.html).
     * 
     * @type {number}
     * @memberof TransactionInfoDTOMeta
     */
    feeMultiplier?: number;
    /**
     * 256-bit hash encoded as a 64-character hexadecimal string.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    aggregateHash: string;
    /**
     * Unique identifier of the object in the node's database (MongoDB ObjectId).
     * Used as the `offset` parameter value for cursor-based pagination.
     * 
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    aggregateId: string;
}

/**
 * Check if a given object implements the TransactionInfoDTOMeta interface.
 */
export function instanceOfTransactionInfoDTOMeta(value: Record<string, any>): value is TransactionInfoDTOMeta {
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('merkleComponentHash' in value) || value['merkleComponentHash'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('aggregateHash' in value) || value['aggregateHash'] === undefined) return false;
    if (!('aggregateId' in value) || value['aggregateId'] === undefined) return false;
    return true;
}

export function TransactionInfoDTOMetaFromJSON(json: any): TransactionInfoDTOMeta {
    return TransactionInfoDTOMetaFromJSONTyped(json, false);
}

export function TransactionInfoDTOMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInfoDTOMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'],
        'hash': json['hash'],
        'merkleComponentHash': json['merkleComponentHash'],
        'index': json['index'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'feeMultiplier': json['feeMultiplier'] == null ? undefined : json['feeMultiplier'],
        'aggregateHash': json['aggregateHash'],
        'aggregateId': json['aggregateId'],
    };
}

export function TransactionInfoDTOMetaToJSON(json: any): TransactionInfoDTOMeta {
    return TransactionInfoDTOMetaToJSONTyped(json, false);
}

export function TransactionInfoDTOMetaToJSONTyped(value?: TransactionInfoDTOMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'hash': value['hash'],
        'merkleComponentHash': value['merkleComponentHash'],
        'index': value['index'],
        'timestamp': value['timestamp'],
        'feeMultiplier': value['feeMultiplier'],
        'aggregateHash': value['aggregateHash'],
        'aggregateId': value['aggregateId'],
    };
}

