name: CI Node.js

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 21]
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: git submodule update --init --recursive --remote
      - run: |
          git fetch origin
          git switch main
          git pull --ff-only
          npm install
          npm run build
        working-directory: ./symbol-openapi
      - run: java -version
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli version
      - run: npm install
      - run: npm run openapi:set:version
      - run: npm run openapi:generate
      - run: npm run build
      - run: npm run test
      - name: Dry run publish check (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm publish --dry-run
